alter table TEAMINFO add CMACAUNAME VARCHAR(40);
alter table TEAMINFO add CHKJCNAME VARCHAR(40);
alter table TEAMINFO add LASTUPDATE TIMESTAMP;

alter table LEAGINFO add CMACAUNAME VARCHAR(40);
alter table LEAGINFO add CHKJCNAME VARCHAR(40);
alter table LEAGINFO add LASTUPDATE TIMESTAMP;


alter table HK_QUEUE drop BINQUERY;
alter table HK_QUEUE add BINQUERY BLOB SUB_TYPE TEXT SEGMENT SIZE 1000;

alter table CHK_QUEUE drop CQUERY;
alter table CHK_QUEUE add CQUERY VARCHAR(10) NOT NULL;
alter table CHK_QUEUE alter CQUERY position 3;
alter table CHK_QUEUE drop BINQUERY;
alter table CHK_QUEUE add BINQUERY BLOB SUB_TYPE TEXT SEGMENT SIZE 2048;

alter table CHK_QUEUE drop CQUERY;
alter table CHK_QUEUE add CQUERY VARCHAR(1000) NOT NULL;
alter table CHK_QUEUE alter CQUERY position 3;
alter table CHK_QUEUE drop BINQUERY;
alter table CHK_QUEUE add BINQUERY BLOB SUB_TYPE TEXT SEGMENT SIZE 1000;