CREATE TABLE BIGSMALLODDS_INFO 
(
  IMATCH_CNT	INTEGER NOT NULL,
  CACT	VARCHAR(1),
  CSCORE	VARCHAR(6),
  CBIGODDS	VARCHAR(5),
  CSMALLODDS	VARCHAR(5),
  CSTATUS VARCHAR(1),
  IIMPORTSIZE INTEGER,
  IORDER_NO INTEGER,
CONSTRAINT PKBIGSMALL PRIMARY KEY (IMATCH_CNT)
);
grant all on BIGSMALLODDS_INFO to public;
commit;

Remark: alter table BIGSMALLODDS_INFO alter CSCORE type VARCHAR(6);
Remark: alter table BIGSMALLODDS_INFO add CSTATUS VARCHAR(1);
Remark: alter table BIGSMALLODDS_INFO add IIMPORTSIZE INTEGER;

Remark: alter table BIGSMALLODDS_INFO add IORDER_NO INTEGER;
Remark: alter table BIGSMALLODDS_INFO alter IORDER_NO POSITION 1;
Remark: CREATE INDEX BSODDSIDX1 ON BIGSMALLODDS_INFO(IORDER_NO);