CREATE GENERATOR MCID_GEN;
SET GENERATOR MCID_GEN TO 0;	  //reset generator to 0
COMMIT;

SET TERM !! ;
create trigger autoinc_MCID for ASIAODDSMATCH_INFO
before insert as
begin
new.IMATCH_ID = GEN_ID(MCID_GEN, 1);
end!!
SET TERM ;!!
commit;

drop trigger autoinc_MCID;

DELETE FROM RDB$GENERATOR WHERE RDB$GENERATOR_NAME = 'MCID_GEN';

insert into ASIAODDSMATCH_INFO (CHOST, CGUEST, CLEAGUE, CLEAGUEALIAS, CCOMPANY, MATCHDATETIME, CMATCH_FIELD, CHOSTRANK, CGUESTRANK, LASTUPDATE) 
values ('host','guest','league','alias','company',MATCHDATETIME,'0','1','¤A3',CURRENT_TIMESTAMP);

select GEN_ID(LOG_ADMIN_SEQ_GEN,0) from RDB$DATABASE