CREATE TABLE HKJCSOCCRS_INFO 
(
  IMATCH_CNT	INTEGER NOT NULL,
  IHOME_SCORE	INTEGER NOT NULL,
	IAWAY_SCORE	INTEGER NOT NULL,
	CODDS				VARCHAR(6),
CONSTRAINT PKHKJCSOCCRS PRIMARY KEY (IMATCH_CNT, IHOME_SCORE, IAWAY_SCORE)
);