CREATE TABLE HKJCSOCCER_INFO 
(
  IMATCH_CNT	INTEGER NOT NULL,
  CLEAGUEALIAS	VARCHAR(6) NOT NULL,
  CLEAGUE	VARCHAR(24) NOT NULL,
  CHOST	VARCHAR(8) NOT NULL,
  CGUEST	VARCHAR(8) NOT NULL,
  MATCHDATETIME	TIMESTAMP NOT NULL,
  IWEEK	INTEGER NOT NULL,
  ISEQ_NO	INTEGER NOT NULL,
  CFIELD	VARCHAR(1),
  CHOST_HANDI	VARCHAR(1),
  CSTATUS	VARCHAR(1),
  CACT	VARCHAR(1),
CONSTRAINT PKHKJCSOCMAIN PRIMARY KEY (IMATCH_CNT),
CONSTRAINT HKJCSOCMAIN_UNI UNIQUE (CLEAGUEALIAS, CLEAGUE, CHOST, CGUEST, MATCHDATETIME, IWEEK, ISEQ_NO)
);