CREATE TABLE LIVEODDS_CFG 
(
  IREGION_ID	INTEGER NOT NULL,
  CREGION	VARCHAR(10) NOT NULL,
  IORDER	INTEGER,
CONSTRAINT PKLIVEODDSCFG PRIMARY KEY (IREGION_ID)
);
grant all on LIVEODDS_CFG to public;
commit;

INSERT INTO LIVEODDS_CFG (IREGION_ID, CREGION, IORDER) VALUES (1, '亞洲', 1);
INSERT INTO LIVEODDS_CFG (IREGION_ID, CREGION, IORDER) VALUES (2, '澳門', 2);
INSERT INTO LIVEODDS_CFG (IREGION_ID, CREGION, IORDER) VALUES (3, '大馬', 3);
INSERT INTO LIVEODDS_CFG (IREGION_ID, CREGION, IORDER) VALUES (4, '柬埔寨', 4);

CREATE INDEX LIVEODDSCFGX1 ON LIVEODDS_CFG(IORDER);
CREATE INDEX LIVEODDSCFGX2 ON LIVEODDS_CFG(CREGION);