CREATE TABLE LIVEODDS_INFO 
(
	IMATCH_CNT	INTEGER NOT NULL,
	IREGION_ID	INTEGER NOT NULL,
	CLEAGUE	VARCHAR(24) NOT NULL,
  CALIAS	VARCHAR(6) NOT NULL,
  CHOST	VARCHAR(8) NOT NULL,
  CGUEST	VARCHAR(8) NOT NULL,
  CACT	VARCHAR(1) NOT NULL,
  IMATCHORDER INTEGER,
  CMATCHDATE	VARCHAR(8),
  CMATCHTIME	VARCHAR(4),
  CMATCHSTATUS	VARCHAR(1),
  CMATCHFIELD	VARCHAR(1),
  CHOST_HANDI	VARCHAR(1),
  IH_SCORE	INTEGER,
  IG_SCORE	INTEGER,
  CH_WEAR	VARCHAR(10),
  CG_WEAR	VARCHAR(10),
  ITIMEOFGAME	INTEGER,
  CHANDICAP1	VARCHAR(3),
  CHANDICAP2	VARCHAR(3),
  CHODDS	VARCHAR(6),
  CTOTALSCORE VARCHAR(6),
  CBIGODDS	VARCHAR(5),
  CSMALLODDS	VARCHAR(5),
  CODDSSTATUS	VARCHAR(1),
  CONSTRAINT PKLIVEODDS PRIMARY KEY (IMATCH_CNT, IREGION_ID)
);
grant all on LIVEODDS_INFO to public;

DROP INDEX LVODDS_COUNTX;
DROP INDEX LVODDS_IDX;
DROP INDEX LVODDS_LEAGX;
CREATE INDEX LIVEODDSX1 ON LIVEODDS_INFO(IMATCHORDER);
CREATE INDEX LIVEODDSX2 ON LIVEODDS_INFO(CACT);