CREATE GENERATOR LOG_ADMIN_SEQ_GEN;
SET GENERATOR LOG_ADMIN_SEQ_GEN TO 0;
COMMIT;

create table LOG_ADMINTASK
(
  ISEQ_NO INTEGER NOT NULL,
  TIMEFLAG TIMESTAMP NOT NULL,
  SECTION VARCHAR(10) NOT NULL,
  CMD VARCHAR(20),
  PARAM VARCHAR(500),
  BATCHJOB VARCHAR(60),
  CONSTRAINT LOG_ADMIN_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_ADMINTASK to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_ADMIN_SEQ for LOG_ADMINTASK
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_ADMIN_SEQ_GEN, 1);
end!!
SET TERM ;!!
commit;

Remark: if required
alter table LOG_ADMINTASK add BATCHJOB VARCHAR(60);