CREATE GENERATOR LOG_BLKMSG_SEQ_GEN;
SET GENERATOR LOG_BLKMSG_SEQ_GEN TO 0;
COMMIT;

create table LOG_BLANKMESSAGE
(
  ISEQ_NO INTEGER NOT NULL,
  TIMEFLAG TIMESTAMP NOT NULL,
  IITEMSEQ_NO INTEGER,
  SECTION VARCHAR(11) NOT NULL,
  MsgType VARCHAR(10),
  MsgContent VARCHAR(100),
  BATCHJOB VARCHAR(60),
  CONSTRAINT LOG_BLKMSG_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_BLANKMESSAGE to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_BLKMSG_SEQ for LOG_BLANKMESSAGE
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_BLKMSG_SEQ_GEN, 1);
end!!
SET TERM ;!!
commit;