CREATE GENERATOR LOG_RANK_SEQ_GEN;
SET GENERATOR LOG_RANK_SEQ_GEN TO 0;
COMMIT;

create table LOG_RANK
(
  ISEQ_NO INTEGER NOT NULL,
  TIMEFLAG TIMESTAMP NOT NULL,
  SECTION VARCHAR(13) NOT NULL,
  LeagueAlias VARCHAR(8) NOT NULL,
  ACT VARCHAR(1),
  IITEMSEQ_NO INTEGER,
  RANK INTEGER,
  TEAM VARCHAR(8),
  SCORE INTEGER,
  EVENTCNT INTEGER,
  BATCHJOB VARCHAR(60),
  CONSTRAINT LOG_RANK_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_RANK to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_RANK_SEQ for LOG_RANK
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_RANK_SEQ_GEN, 1);
end!!
SET TERM ;!!
commit;

Remark: if required
alter table LOG_RANK add BATCHJOB VARCHAR(60);