CREATE GENERATOR LOG_BSODDS_SEQ_GEN;
SET GENERATOR LOG_BSODDS_SEQ_GEN TO 0;
COMMIT;

create table LOG_BIGSMALLODDS
(
  ISEQ_NO INTEGER NOT NULL,
  TIMEFLAG TIMESTAMP NOT NULL,
  SECTION VARCHAR(15) NOT NULL,
  League VARCHAR(20) NOT NULL,
  Host VARCHAR(8) NOT NULL,
  Guest VARCHAR(8) NOT NULL,
  Act VARCHAR(1),
  MatchDate VARCHAR(8),
  MatchTime VARCHAR(4),
  TotalScore VARCHAR(6),
  BigOdds VARCHAR(5),
  SmallOdds VARCHAR(5),
  BATCHJOB VARCHAR(60),
  CONSTRAINT LOG_BSODDS_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_BIGSMALLODDS to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_BSODDS_SEQ for LOG_BIGSMALLODDS
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_BSODDS_SEQ_GEN, 1);
end!!
SET TERM ;!!
commit;

Remark: if required
alter table LOG_BIGSMALLODDS add BATCHJOB VARCHAR(60);
alter table LOG_BIGSMALLODDS alter TotalScore type VARCHAR(6);