CREATE GENERATOR LOG_MODOTH_SEQ_GEN;
SET GENERATOR LOG_MODOTH_SEQ_GEN TO 0;
COMMIT;

create table LOG_OTHERODDSMATCHMODIFY
(
  ISEQ_NO INTEGER NOT NULL,
  TIMEFLAG TIMESTAMP NOT NULL,
  SECTION VARCHAR(10) NOT NULL,
  CMD VARCHAR(20) NOT NULL,
  PARAM1 VARCHAR(20),
  PARAM2 VARCHAR(20),
  PARAM3 VARCHAR(20),
  PARAM4 VARCHAR(20),
  PARAM5 VARCHAR(20),
  PARAM6 VARCHAR(20),
  PARAM7 VARCHAR(20),
  PARAM8 VARCHAR(20),
  PARAM9 VARCHAR(20),
  PARAM10 VARCHAR(20),
  BATCHJOB VARCHAR(60),
  CONSTRAINT LOG_MODOTH_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_OTHERODDSMATCHMODIFY to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_MODOTH_SEQ for LOG_OTHERODDSMATCHMODIFY
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_MODOTH_SEQ_GEN, 1);
end!!
SET TERM ;!!
commit;

Remark: if required
alter table LOG_OTHERODDSMATCHMODIFY add BATCHJOB VARCHAR(60);