CREATE GENERATOR LOG_MODMAH_SEQ_GEN;
SET GENERATOR LOG_MODMAH_SEQ_GEN TO 0;
COMMIT;

create table LOG_MODIFYMATCH
(
  ISEQ_NO INTEGER NOT NULL,
  TIMEFLAG TIMESTAMP NOT NULL,
  SECTION VARCHAR(10) NOT NULL,
  CMD VARCHAR(20) NOT NULL,
  PARAM1 VARCHAR(20),
  PARAM2 VARCHAR(20),
  PARAM3 VARCHAR(20),
  PARAM4 VARCHAR(20),
  PARAM5 VARCHAR(20),
  PARAM6 VARCHAR(20),
  PARAM7 VARCHAR(20),
  PARAM8 VARCHAR(20),
  PARAM9 VARCHAR(20),
  PARAM10 VARCHAR(20),
  PARAM11 VARCHAR(20),
  PARAM12 VARCHAR(20),
  PARAM13 VARCHAR(20),
  PARAM14 VARCHAR(20),
  PARAM15 VARCHAR(20),
  PARAM16 VARCHAR(20),
  PARAM17 VARCHAR(20),
  PARAM18 VARCHAR(20),
  BATCHJOB VARCHAR(60),
  CONSTRAINT LOG_MODMAH_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_MODIFYMATCH to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_MODMAH_SEQ for LOG_MODIFYMATCH
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_MODMAH_SEQ_GEN, 1);
end!!
SET TERM ;!!
commit;

Remark: if required
alter table LOG_MODIFYMATCH add BATCHJOB VARCHAR(60);