CREATE GENERATOR LOG_MENU_SEQ_GEN;
SET GENERATOR LOG_MENU_SEQ_GEN TO 0;
COMMIT;

create table LOG_MENU
(
  ISEQ_NO INTEGER NOT NULL,
  TIMEFLAG TIMESTAMP NOT NULL,
  SECTION VARCHAR(6) NOT NULL,
  MENU VARCHAR(500),
  BATCHJOB VARCHAR(60),
  CONSTRAINT LOG_MENU_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_MENU to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_MENU_SEQ for LOG_MENU
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_MENU_SEQ_GEN, 1);
end!!
SET TERM ;!!
commit;

INSERT INTO ADMINCFG (IADMIN_NO, CCATEGORY, CDISPLAY, CCMD_TYPE, CPARAM) VALUES (47, '足球1', '分析->賽程', 'CLR_TBL', 'NEWS-20');
INSERT INTO ADMINCFG (IADMIN_NO, CCATEGORY, CDISPLAY, CCMD_TYPE, CPARAM) VALUES (48, '足球1', '分析->新聞', 'CLR_TBL', 'NEWS-21');
INSERT INTO ADMINCFG (IADMIN_NO, CCATEGORY, CDISPLAY, CCMD_TYPE, CPARAM) VALUES (49, '足球1', '足彩', 'CLR_TBL', 'NEWS-39');
INSERT INTO ADMINCFG (IADMIN_NO, CCATEGORY, CDISPLAY, CCMD_TYPE, CPARAM) VALUES (50, '籃球', '分析', 'CLR_TBL', 'NEWS-15');
INSERT INTO ADMINCFG (IADMIN_NO, CCATEGORY, CDISPLAY, CCMD_TYPE, CPARAM) VALUES (51, '籃球', '新聞', 'CLR_TBL', 'NEWS-16');
INSERT INTO ADMINCFG (IADMIN_NO, CCATEGORY, CDISPLAY, CCMD_TYPE, CPARAM) VALUES (52, '籃球', '直播', 'CLR_TBL', 'NEWS-17');
INSERT INTO ADMINCFG (IADMIN_NO, CCATEGORY, CDISPLAY, CCMD_TYPE, CPARAM) VALUES (53, '籃球', '記錄', 'CLR_TBL', 'NEWS-18');
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (1, 47, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (1, 48, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (1, 49, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (1, 50, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (1, 51, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (1, 52, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (1, 53, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (3, 41, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (3, 43, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (5, 5, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (5, 6, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (5, 7, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (5, 19, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (5, 20, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (5, 21, CURRENT_TIMESTAMP);