CREATE GENERATOR LOG_CRS_SEQ_GEN;
SET GENERATOR LOG_CRS_SEQ_GEN TO 0;
COMMIT;

create table LOG_CORRECTSCORE
(
  ISEQ_NO INTEGER NOT NULL,
  TIMEFLAG TIMESTAMP NOT NULL,
  IITEMSEQ_NO INTEGER,
  SECTION VARCHAR(15) NOT NULL,
  League VARCHAR(18) NOT NULL,
  Host VARCHAR(8) NOT NULL,
  Guest VARCHAR(8) NOT NULL,
  Act VARCHAR(1),
  MatchDate VARCHAR(8),
  MatchTime VARCHAR(4),
  MatrixSize INTEGER,
  Odds VARCHAR(5),
  BATCHJOB VARCHAR(60),
  CONSTRAINT LOG_CRS_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_CORRECTSCORE to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_CRS_SEQ for LOG_CORRECTSCORE
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_CRS_SEQ_GEN, 1);
end!!
SET TERM ;!!
commit;

Remark: if required
alter table LOG_CORRECTSCORE add BATCHJOB VARCHAR(60);