CREATE GENERATOR LOG_ANLYREMK_GEN;
SET GENERATOR LOG_ANLYREMK_GEN TO 0;
COMMIT;

create table LOG_ANALYSISREMARKS
(
  ISEQ_NO INTEGER NOT NULL,
  TIMEFLAG TIMESTAMP NOT NULL,
  SECTION VARCHAR(18) NOT NULL,
  Act VARCHAR(1),
  League VARCHAR(18) NOT NULL,
  Host VARCHAR(8) NOT NULL,
  Guest VARCHAR(8) NOT NULL,
  Remarks VARCHAR(300),
  BATCHJOB VARCHAR(60),
  CONSTRAINT LOG_ANLYREMK_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_ANALYSISREMARKS to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_ANLYREMARKS_SEQ for LOG_ANALYSISREMARKS
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_ANLYREMK_GEN, 1);
end!!
SET TERM ;!!
commit;

Remark: if required
alter table LOG_ANALYSISREMARKS add BATCHJOB VARCHAR(60);