CREATE GENERATOR LOG_ANLYRECN_GEN;
SET GENERATOR LOG_ANLYRECN_GEN TO 0;
COMMIT;

create table LOG_ANALYSISRECENT
(
  ISEQ_NO	INTEGER NOT NULL,
  TIMEFLAG	TIMESTAMP NOT NULL,
  IITEMSEQ_NO	INTEGER,
  SECTION	VARCHAR(18) NOT NULL,
  ACT	VARCHAR(1),
  LEAGUE	VARCHAR(18) NOT NULL,
  HOST	VARCHAR(8) NOT NULL,
  GUEST	VARCHAR(8) NOT NULL,
  MATCHDATE	VARCHAR(8),
  MATCHTIME	VARCHAR(4),
  MATCHFIELD	VARCHAR(1),
  HOSTHANDICAP	VARCHAR(1),
  RECENTTYPE	VARCHAR(1),
  RECENTALIAS	VARCHAR(6),
  RECENTCHALLENGER	VARCHAR(10),
  RECENTFIELD	VARCHAR(2),
  RECENTHOSTSCORE	INTEGER,
  RECENTGUESTSCORE	INTEGER,
  BATCHJOB	VARCHAR(60),
  CONSTRAINT LOG_ANLYRECN_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_ANALYSISRECENT to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_ANLYRECN_SEQ for LOG_ANALYSISRECENT
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_ANLYRECN_GEN, 1);
end!!
SET TERM ;!!
commit;

Remark: if required
alter table LOG_ANALYSISRECENT add MatchDate VARCHAR(8);
alter table LOG_ANALYSISRECENT add MatchTime VARCHAR(4);
alter table LOG_ANALYSISRECENT add MatchField VARCHAR(1);
alter table LOG_ANALYSISRECENT add HostHandicap VARCHAR(1);
commit;
alter table LOG_ANALYSISRECENT alter MatchDate POSITION 8;
alter table LOG_ANALYSISRECENT alter MatchTime POSITION 9;
alter table LOG_ANALYSISRECENT alter MatchField POSITION 10;
alter table LOG_ANALYSISRECENT alter HostHandicap POSITION 11;
commit;