CREATE GENERATOR LOG_ANLYPLY_SEQ_GEN;
SET GENERATOR LOG_ANLYPLY_SEQ_GEN TO 0;
COMMIT;

create table LOG_ANALYSISPLAYERS
(
  ISEQ_NO INTEGER NOT NULL,
  TIMEFLAG TIMESTAMP NOT NULL,
  IITEMSEQ_NO INTEGER,
  SECTION VARCHAR(18) NOT NULL,
  Act VARCHAR(1),
  League VARCHAR(18) NOT NULL,
  Host VARCHAR(8) NOT NULL,
  Guest VARCHAR(8) NOT NULL,
  PlayerType VARCHAR(1),
  PlayerName VARCHAR(10),
  PlayerNo INTEGER,
  PlayerPos VARCHAR(4),
  BATCHJOB VARCHAR(60),
  CONSTRAINT LOG_ANLYPLY_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_ANALYSISPLAYERS to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_ANLYPLY_SEQ for LOG_ANALYSISPLAYERS
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_ANLYPLY_SEQ_GEN, 1);
end!!
SET TERM ;!!
commit;

Remark: if required
alter table LOG_ANALYSISPLAYERS add BATCHJOB VARCHAR(60);