CREATE GENERATOR LOG_ALTMSG_SEQ_GEN;
SET GENERATOR LOG_ALTMSG_SEQ_GEN TO 0;
COMMIT;

create table LOG_ALERTMSG
(
  ISEQ_NO INTEGER NOT NULL,
  TIMEFLAG TIMESTAMP NOT NULL,
  SECTION VARCHAR(9) NOT NULL,
  MSG_1 VARCHAR(500),
  BATCHJOB VARCHAR(60),
  CONSTRAINT LOG_ALTMSG_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_ALERTMSG to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_ALTMSG_SEQ for LOG_ALERTMSG
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_ALTMSG_SEQ_GEN, 1);
end!!
SET TERM ;!!
commit;