CREATE GENERATOR LOG_REPORT_GEN;
SET GENERATOR LOG_REPORT_GEN TO 0;
COMMIT;

create table LOG_REPORT
(
  ISEQ_NO INTEGER NOT NULL,
  TIMEFLAG TIMESTAMP NOT NULL,
  IITEMSEQ_NO INTEGER,
  SECTION VARCHAR(10) NOT NULL,
  Act VARCHAR(1),
  League VARCHAR(18) NOT NULL,
  Host VARCHAR(8) NOT NULL,
  Guest VARCHAR(8) NOT NULL,
  MatchDate VARCHAR(8),
  MatchTime VARCHAR(4),
  MatchField VARCHAR(1),
  Fixture VARCHAR(20),
  Attention INTEGER,
  Attention_Rate VARCHAR(4),
  Comment VARCHAR(400),
  BATCHJOB VARCHAR(60),
  CONSTRAINT LOG_REPORT_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_REPORT to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_REPORT_SEQ for LOG_REPORT
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_REPORT_GEN, 1);
end!!
SET TERM ;!!
commit;