CREATE GENERATOR LOG_ANLYHIS_SEQ_GEN;
SET GENERATOR LOG_ANLYHIS_SEQ_GEN TO 0;
COMMIT;

create table LOG_ANALYSISHISTORY
(
  ISEQ_NO INTEGER NOT NULL,
  TIMEFLAG TIMESTAMP NOT NULL,
  IITEMSEQ_NO INTEGER,
  SECTION VARCHAR(18) NOT NULL,
  Act VARCHAR(1),
  League VARCHAR(18) NOT NULL,
  Host VARCHAR(8) NOT NULL,
  Guest VARCHAR(8) NOT NULL,
  MatchDate VARCHAR(6),
  LeagueAlias VARCHAR(8),
  MatchField VARCHAR(2),
  HostScore INTEGER,
  GuestScore INTEGER,
  BATCHJOB VARCHAR(60),
  CONSTRAINT LOG_ANLYHIS_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_ANALYSISHISTORY to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_ANLYHIS_SEQ for LOG_ANALYSISHISTORY
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_ANLYHIS_SEQ_GEN, 1);
end!!
SET TERM ;!!
commit;

Remark: if required
alter table LOG_ANALYSISHISTORY add BATCHJOB VARCHAR(60);