CREATE GENERATOR LOG_OTHGOAL_SEQ_GEN;
SET GENERATOR LOG_OTHGOAL_SEQ_GEN TO 0;
COMMIT;

create table LOG_OTHERGOAL
(
  ISEQ_NO INTEGER NOT NULL,
  TIMEFLAG TIMESTAMP NOT NULL,
  IITEMSEQ_NO INTEGER,
  SECTION VARCHAR(10) NOT NULL,
  League VARCHAR(18) NOT NULL,
  LeagueAlias VARCHAR(8) NOT NULL,
  Host VARCHAR(8) NOT NULL,
  Guest VARCHAR(8) NOT NULL,
  Act VARCHAR(1),
  H_Goal INTEGER,
  G_Goal INTEGER,
  Status VARCHAR(4),
  MatchDate VARCHAR(8),
  MatchTime VARCHAR(4),
  Alert VARCHAR(1),
  BATCHJOB VARCHAR(60),
  CONSTRAINT LOG_OTHGOAL_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_OTHERGOAL to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_OTHGOAL_SEQ for LOG_OTHERGOAL
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_OTHGOAL_SEQ_GEN, 1);
end!!
SET TERM ;!!
commit;

Remark: if required
alter table LOG_OTHERGOAL add BATCHJOB VARCHAR(60);