CREATE GENERATOR LOG_MATLIST_SEQ_GEN;
SET GENERATOR LOG_MATLIST_SEQ_GEN TO 0;
COMMIT;

create table LOG_MATCHLIST
(
  ISEQ_NO INTEGER NOT NULL,
  TIMEFLAG TIMESTAMP NOT NULL,
  SECTION VARCHAR(12) NOT NULL,
  IAPP_ID	INTEGER NOT NULL,
  League VARCHAR(24),
  Host VARCHAR(8),
  Guest VARCHAR(8),
  BATCHJOB VARCHAR(60),
  CONSTRAINT LOG_MATLIST_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_MATCHLIST to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_MATLIST_SEQ for LOG_MATCHLIST
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_MATLIST_SEQ_GEN, 1);
end!!
SET TERM ;!!
commit;

Remark: if required
alter table LOG_MATCHLIST add BATCHJOB VARCHAR(60);