CREATE GENERATOR LOG_SCORERS_SEQ_GEN;
SET GENERATOR LOG_SCORERS_SEQ_GEN TO 0;
COMMIT;

create table LOG_SCORERS
(
  ISEQ_NO INTEGER NOT NULL,
  TIMEFLAG TIMESTAMP NOT NULL,
  SECTION VARCHAR(10) NOT NULL,
  ALIAS VARCHAR(8) NOT NULL,
  ACT VARCHAR(1),
  IITEMSEQ_NO INTEGER,
  RANK INTEGER,
  TEAMABBR VARCHAR(3),
  PLAYER VARCHAR(10),
  GOALS INTEGER,
  BATCHJOB VARCHAR(60),
  CONSTRAINT LOG_SCORERS_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_SCORERS to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_SCORERS_SEQ for LOG_SCORERS
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_SCORERS_SEQ_GEN, 1);
end!!
SET TERM ;!!
commit;

alter table LOG_SCORERS alter TEAMABBR type varchar(4);