CREATE GENERATOR LOG_LVODDS_SEQ_GEN;
SET GENERATOR LOG_LVODDS_SEQ_GEN TO 0;
COMMIT;

create table LOG_LIVEODDS
(
  ISEQ_NO	INTEGER NOT NULL,
  TIMEFLAG	TIMESTAMP NOT NULL,
  SECTION	VARCHAR(10) NOT NULL,
  LEAGUEALIAS	VARCHAR(6) NOT NULL,
  LEAGUE	VARCHAR(18) NOT NULL,
  HOST	VARCHAR(8) NOT NULL,
  GUEST	VARCHAR(8) NOT NULL,
  MATCHFIELD	VARCHAR(1),
  HANDICAP	VARCHAR(1),
  MATCHSTATUS VARCHAR(1),
  ACT	VARCHAR(1),
  H_GOAL	INTEGER,
  G_GOAL	INTEGER,
  CURRTIME	INTEGER,
  HANDI	VARCHAR(10),
  ODDS	VARCHAR(10),
  ODDSSTATUS	VARCHAR(10),
  ALERT	INTEGER,
  REGIONID	INTEGER,
  HOSTWEAR	VARCHAR(10),
  GUESTWEAR	VARCHAR(10),
  TOTALSCORE	VARCHAR(6),
  BIGSMALLODDS	VARCHAR(11),
  BATCHJOB	VARCHAR(60),
  CONSTRAINT LOG_LVODDS_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_LIVEODDS to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_LVODDS_SEQ for LOG_LIVEODDS
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_LVODDS_SEQ_GEN, 1);
end!!
SET TERM ;!!
commit;

Remark: if required
alter table LOG_LIVEODDS add MATCHSTATUS VARCHAR(1);
commit;
alter table LOG_LIVEODDS alter MATCHSTATUS POSITION 9;
commit;