CREATE GENERATOR LOG_CHART_SEQ_GEN;
SET GENERATOR LOG_CHART_SEQ_GEN TO 0;
COMMIT;

create table LOG_CHARTRESEND
(
  ISEQ_NO INTEGER NOT NULL,
  TIMEFLAG TIMESTAMP NOT NULL,
  SECTION VARCHAR(14) NOT NULL,
  League VARCHAR(20),
  Host VARCHAR(8),
  Guest VARCHAR(8),
  BATCHJOB VARCHAR(60),
  CONSTRAINT LOG_CHART_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);
grant all on LOG_CHARTRESEND to public;
commit;

SET TERM !! ;
create trigger AUTO_LOG_CHART_SEQ for LOG_CHARTRESEND
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_CHART_SEQ_GEN, 1);
end!!
SET TERM ;!!
commit;