CREATE TABLE LOGININFO 
(
  USER_ID	INTEGER NOT NULL,
  USERNAME	CHAR(20) NOT NULL,
  PWD	CHAR(15),
  ACCESS_RIGHT	CHAR(3),
  ACCESS_START	TIMESTAMP,
  ACCESS_END	TIMESTAMP,
 UNIQUE (USERNAME),
 PRIMARY KEY (USER_ID)
);


alter table LOGININFO drop DESCRIPTION;
alter table LOGININFO add ACCESS_START TIMESTAMP;
alter table LOGININFO add ACCESS_END TIMESTAMP;