create table MENUMAP
(
	IPATH_ID INTEGER NOT NULL,
	ITYPE_ID INTEGER NOT NULL,
	IGROUP_ID INTEGER NOT NULL,
  IKEY_NO INTEGER NOT NULL,
  CONSTRAINT MENUMAP_PK PRIMARY KEY (IPATH_ID, ITYPE_ID, IGROUP_ID, IKEY_NO)
);
grant all on MENUMAP to public;
commit;