create table MENUSRCTARGET_MAP
(
  IPATH_ID INTEGER NOT NULL,
  ITARGET_ID INTEGER NOT NULL,
  CONSTRAINT MENUST_MAP_PK PRIMARY KEY (IPATH_ID, ITARGET_ID)
);
grant all on MENUSRCTARGET_MAP to public;
commit;

Remarks:	IPATH_ID = source path ID in MENUSOURCE_CFG; ITARGET_ID = taget path ID in DISPATCHER