CREATE TABLE REPORT_INFO 
(
	IREC_NO	INTEGER NOT NULL,
	CLEAGUE	VARCHAR(18) NOT NULL,
  CHOST	VARCHAR(8) NOT NULL,
  CGUEST	VARCHAR(8) NOT NULL,
  CACT	VARCHAR(1) NOT NULL,
  CMATCH_VENUE	VARCHAR(20),
  IATTENTION	INTEGER,
  CATTENTION_RATE	VARCHAR(4),
  CREPORT	VARCHAR(400),
  CONSTRAINT PKREPORT PRIMARY KEY (IREC_NO),
  CONSTRAINT UNIREPORT UNIQUE (CLEAGUE, CHOST, CGUEST)
);
grant all on REPORT_INFO to public;
commit;
CREATE INDEX REPORTX1 ON REPORT_INFO(CACT);
commit;