Remark: Reset LOG Table Generator
SET GENERATOR LOG_ADMIN_SEQ_GEN TO 1;
SET GENERATOR LOG_ALLODDS_SEQ_GEN TO 1;
SET GENERATOR LOG_ANLYBG_GEN TO 1;
SET GENERATOR LOG_ANLYHIS_SEQ_GEN TO 1;
SET GENERATOR LOG_ANLYPLY_SEQ_GEN TO 1;
SET GENERATOR LOG_ANLYRECN_GEN TO 1;
SET GENERATOR LOG_ANLYREMK_GEN TO 1;
SET GENERATOR LOG_ANLYSTAT_GEN TO 1;
SET GENERATOR LOG_BSODDS_SEQ_GEN TO 1;
SET GENERATOR LOG_CRS_SEQ_GEN TO 1;
SET GENERATOR LOG_GOALDTL_SEQ_GEN TO 1;
SET GENERATOR LOG_LVGOAL_SEQ_GEN TO 1;
SET GENERATOR LOG_LVODDS_SEQ_GEN TO 1;
SET GENERATOR LOG_MATLIST_SEQ_GEN TO 1;
SET GENERATOR LOG_MODMAH_SEQ_GEN TO 1;
SET GENERATOR LOG_OTHGOAL_SEQ_GEN TO 1;
SET GENERATOR LOG_OTHODDS_SEQ_GEN TO 1;
SET GENERATOR LOG_RANK_SEQ_GEN TO 1;
SET GENERATOR LOG_SPTNEWS_SEQ_GEN TO 1;

Remark: Reset Sequence No in Message Dispatcher Table
update MSGFLAG set LASTSEQ=0;