CREATE TABLE SCORERS_INFO 
(
  CLEAG_ID	VARCHAR(3) NOT NULL,
  CTEAM_ID	VARCHAR(3) NOT NULL,
	CPLAYER_NAME	VARCHAR(10) NOT NULL,
  CTEAM_ABBR	VARCHAR(4),
  CACT VARCHAR(1) default 'U',
  IRID INTEGER,
  IRANK	INTEGER,
  IGOALS INTEGER,
 CONSTRAINT SCORERS_PK PRIMARY KEY (CLEAG_ID, CTEAM_ID, CPLAYER_NAME)
);

create index SCORERSIDX1 on SCORERS_INFO(IRANK);
create index SCORERSIDX2 on SCORERS_INFO(IRID);

INSERT INTO SCORERS_INFO (CLEAG_ID, CTEAM_ID, CPLAYER_NAME, CTEAM_ABBR, IRANK, IGOALS, IRID) VALUES ('001', '002', '§Bª÷', 'ªü', 1, 12, 0);
INSERT INTO SCORERS_INFO (CLEAG_ID, CTEAM_ID, CPLAYER_NAME, CTEAM_ABBR, IRANK, IGOALS, IRID) VALUES ('001', '001', '¬ìÄõ', '°Ò', 2, 10, 1);