Remark: ASP.NET (Alert Message, Chart Resend) ASIA_SOCCER_DB.GDB
CREATE TABLE LOG_CHARTRESEND

Rearrange PATH_ID

update ADMINSVCMAP set ISVC_NO=8 where ISVC_NO=5;
update ADMINSVCMAP set ISVC_NO=5 where ISVC_NO=4;
update ADMINSVCMAP set ISVC_NO=4 where ISVC_NO=3;
update ADMINSVCMAP set ISVC_NO=3 where ISVC_NO=8;

update SVCCFG set ISVC_NO=8 where ISVC_NO=5;
update SVCCFG set ISVC_NO=5 where ISVC_NO=4;
update SVCCFG set ISVC_NO=4 where ISVC_NO=3;
update SVCCFG set ISVC_NO=3 where ISVC_NO=8;
INSERT INTO SVCCFG (ISVC_NO, CSVC_NAME, CACCESS_RIGHT) VALUES (6, '°¨·| Handler 2', '011');
update SVCCFG set CSVC_NAME='GOGO1 Sender' where ISVC_NO=1;

INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (6, 5, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (6, 6, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (6, 7, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (6, 19, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (6, 20, CURRENT_TIMESTAMP);
INSERT INTO ADMINSVCMAP (ISVC_NO, IADMIN_NO, LASTUPDATE) VALUES (6, 21, CURRENT_TIMESTAMP);

update MENUSRCTARGET_MAP set ITARGET_ID=4 where IPATH_ID=2;

Remark: Message Dispatcher (HKJC version) DISPATCHER.GDB
Rearrange PATH_ID

CREATE TABLE NEWSFILTER_GOGO
CREATE TABLE NEWSFILTER_HKJC

update IOPATH set IPATH_ID=10 where IPATH_ID=5;
update IOPATH set IPATH_ID=5 where IPATH_ID=4;
update IOPATH set IPATH_ID=4 where IPATH_ID=3;
update IOPATH set IPATH_ID=5 where IPATH_ID=10;

update MSGGPPATH_MAP set IPATH_ID=10 where IPATH_ID=5;
update MSGGPPATH_MAP set IPATH_ID=5 where IPATH_ID=4;
update MSGGPPATH_MAP set IPATH_ID=4 where IPATH_ID=3;
update MSGGPPATH_MAP set IPATH_ID=5 where IPATH_ID=10;

update PREDEFINED_HOSTPATH set IPATH_ID=10 where IPATH_ID=5;
update PREDEFINED_HOSTPATH set IPATH_ID=5 where IPATH_ID=4;
update PREDEFINED_HOSTPATH set IPATH_ID=4 where IPATH_ID=3;
update PREDEFINED_HOSTPATH set IPATH_ID=5 where IPATH_ID=10;

delete from MSGROUTE;
commit;
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('01', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('01', 2);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('01', 5);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('03', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('03', 2);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('04', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('04', 4);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('06', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('06', 2);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('07', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('07', 4);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('07', 6);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('08', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('08', 4);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('08', 6);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('09', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('09', 4);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('09', 6);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('10', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('10', 4);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('10', 6);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('11', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('11', 3);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('11', 6);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('12', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('12', 3);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('12', 6);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('13', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('13', 5);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('14', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('16', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('17', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('18', 2);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('19', 2);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('20', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('21', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('21', 2);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('23', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('23', 2);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('23', 3);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('23', 4);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('07', 3);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('08', 3);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('09', 3);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('10', 3);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('11', 4);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('12', 4);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('14', 4);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('16', 2);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('16', 5);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('18', 5);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('15', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('20', 2);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('20', 5);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('20', 4);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('13', 2);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('13', 4);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('15', 2);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('27', 8);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('27', 7);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('25', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('28', 7);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('25', 4);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('26', 1);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('28', 8);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('29', 8);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('29', 7);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('30', 8);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('30', 7);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('23', 5);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('23', 6);
commit;

INSERT INTO "NEWSFILTER_GOGO" ("IAPP_ID") VALUES (101);
INSERT INTO "NEWSFILTER_GOGO" ("IAPP_ID") VALUES (102);
INSERT INTO "NEWSFILTER_GOGO" ("IAPP_ID") VALUES (103);
INSERT INTO "NEWSFILTER_GOGO" ("IAPP_ID") VALUES (104);
INSERT INTO "NEWSFILTER_GOGO" ("IAPP_ID") VALUES (105);
INSERT INTO "NEWSFILTER_GOGO" ("IAPP_ID") VALUES (106);
INSERT INTO "NEWSFILTER_GOGO" ("IAPP_ID") VALUES (107);
INSERT INTO "NEWSFILTER_GOGO" ("IAPP_ID") VALUES (108);
INSERT INTO "NEWSFILTER_GOGO" ("IAPP_ID") VALUES (109);
INSERT INTO "NEWSFILTER_GOGO" ("IAPP_ID") VALUES (110);

INSERT INTO "NEWSFILTER_HKJC" ("IAPP_ID") VALUES (20);
INSERT INTO "NEWSFILTER_HKJC" ("IAPP_ID") VALUES (22);
INSERT INTO "NEWSFILTER_HKJC" ("IAPP_ID") VALUES (29);
INSERT INTO "NEWSFILTER_HKJC" ("IAPP_ID") VALUES (30);
INSERT INTO "NEWSFILTER_HKJC" ("IAPP_ID") VALUES (31);
INSERT INTO "NEWSFILTER_HKJC" ("IAPP_ID") VALUES (32);
INSERT INTO "NEWSFILTER_HKJC" ("IAPP_ID") VALUES (33);
INSERT INTO "NEWSFILTER_HKJC" ("IAPP_ID") VALUES (34);
INSERT INTO "NEWSFILTER_HKJC" ("IAPP_ID") VALUES (35);
INSERT INTO "NEWSFILTER_HKJC" ("IAPP_ID") VALUES (36);
INSERT INTO "NEWSFILTER_HKJC" ("IAPP_ID") VALUES (37);
INSERT INTO "NEWSFILTER_HKJC" ("IAPP_ID") VALUES (38);
INSERT INTO "NEWSFILTER_HKJC" ("IAPP_ID") VALUES (39);

INSERT INTO "MSG_TYPE" ("IMSG_ID", "CAPP_TYPE", "CMSG_TYPE", "CMSG_DESC") VALUES (33, '07', '26', 'ChartResend.ini');

delete from MSGROUTE where CMSG_TYPE='23';
delete from MSGROUTE where CMSG_TYPE='24';
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('26', 1);

INSERT INTO "MSGGP_MAP" ("IMSG_GP", "IMSG_ID", "LASTUPDATE") VALUES (6, 33, CURRENT_TIMESTAMP);

INSERT INTO MSG_GP (IMSG_GP, CMSG_DESC) VALUES (10, 'HKJC Handler 2 INI notify');

INSERT INTO IOPATH (IPATH_ID, CIO_PATH, CPATH_DESC, CDBCONN, CPENDINGSQL) VALUES (6, 'D:\JCSports\DataFile2\', 'HKJC Handler Path 2', 'Provider=IbOleDb;Location=127.0.0.1;Data Source=D:/JCSports_2G/db/JCSPORTS_2G.GDB;User ID=sysdba;Password=masterkey;Min Pool Size=5;Max Pool Size=100', 'insert into pendingjob2 (pendingfile) values (''PENDINGBATCHFILENAME'')');

INSERT INTO "MSGGPPATH_MAP" ("IMSG_GP", "IPATH_ID") VALUES (10, 6);

delete from MSGGP_MAP where IMSG_GP=3 and IMSG_ID=12;
delete from MSGGP_MAP where IMSG_GP=3 and IMSG_ID=13;
delete from MSGGP_MAP where IMSG_GP=3 and IMSG_ID=14;
delete from MSGGP_MAP where IMSG_GP=3 and IMSG_ID=15;
delete from MSGGP_MAP where IMSG_GP=3 and IMSG_ID=16;
delete from MSGGP_MAP where IMSG_GP=3 and IMSG_ID=17;
INSERT INTO "MSGGP_MAP" ("IMSG_GP", "IMSG_ID", "LASTUPDATE") VALUES (10, 12, CURRENT_TIMESTAMP);
INSERT INTO "MSGGP_MAP" ("IMSG_GP", "IMSG_ID", "LASTUPDATE") VALUES (10, 13, CURRENT_TIMESTAMP);
INSERT INTO "MSGGP_MAP" ("IMSG_GP", "IMSG_ID", "LASTUPDATE") VALUES (10, 14, CURRENT_TIMESTAMP);
INSERT INTO "MSGGP_MAP" ("IMSG_GP", "IMSG_ID", "LASTUPDATE") VALUES (10, 15, CURRENT_TIMESTAMP);
INSERT INTO "MSGGP_MAP" ("IMSG_GP", "IMSG_ID", "LASTUPDATE") VALUES (10, 16, CURRENT_TIMESTAMP);
INSERT INTO "MSGGP_MAP" ("IMSG_GP", "IMSG_ID", "LASTUPDATE") VALUES (10, 17, CURRENT_TIMESTAMP);

update MSGROUTE set IPATH_ID=10 where CMSG_TYPE='07' and IPATH_ID=3;
update MSGROUTE set IPATH_ID=10 where CMSG_TYPE='08' and IPATH_ID=3;
update MSGROUTE set IPATH_ID=10 where CMSG_TYPE='09' and IPATH_ID=3;
update MSGROUTE set IPATH_ID=10 where CMSG_TYPE='10' and IPATH_ID=3;
update MSGROUTE set IPATH_ID=10 where CMSG_TYPE='11' and IPATH_ID=3;
update MSGROUTE set IPATH_ID=10 where CMSG_TYPE='12' and IPATH_ID=3;


Remark: WinMessageDispatcher should be updated
drop table HOSTPATH_MAP;
drop table PREDEFINED_HOSTPATH;