DROP TABLE DISPATCHHOSTS_INFO;
DROP TABLE GENINFO;
DROP TABLE HISTORYINFO;
DROP TABLE PLAYERINFO;
DROP TABLE TEMPHLINFO;
DROP TABLE TEMPODDSINFO;
DROP TABLE TEMPOTHERODDSINFO;

CREATE TABLE DISPATCHHOSTS_INFO 
(
  IHOST_ID	INTEGER NOT NULL,
  CHOSTNAME	VARCHAR(20) NOT NULL,
  CHOSTIP	VARCHAR(15) NOT NULL,
  IHOSTPORT	INTEGER,
  CPROTOCOL	VARCHAR(10) NOT NULL,
  CQUEUENAME	VARCHAR(40) NOT NULL,
  LASTUPDATE	TIMESTAMP,
CONSTRAINT DISPATCHHOST_PK PRIMARY KEY (IHOST_ID),
CONSTRAINT DISPATCHHOST_UNIQUE UNIQUE (CHOSTNAME, CQUEUENAME)
);

CREATE TABLE GENINFO 
(
  MSGID	INTEGER NOT NULL,
  INFODATE	CHAR(8),
  INFOTIME	CHAR(4),
  ACT	CHAR(1),
  FLAG	CHAR(1),
  TITLE	CHAR(40),
  CONTENT	CHAR(240),
 PRIMARY KEY (MSGID)
);

CREATE TABLE HISTORYINFO 
(
  LEAGUE	CHAR(20),
  ALIAS	CHAR(8),
  TEAM	CHAR(10),
  MATCH	CHAR(12),
  WIN	INTEGER,
  LOSS	INTEGER,
  DRAW	INTEGER,
  SCORE_NO	INTEGER,
  MISS_NO	INTEGER,
  SHOOTER0	CHAR(10),
  SCORE0	INTEGER,
  SHOOTER1	CHAR(10),
  SCORE1	INTEGER,
  SHOOTER2	CHAR(10),
  SCORE2	INTEGER,
  GOALKEEPER	CHAR(10),
  MISS	INTEGER,
  FLAG	CHAR(1),
  ACT	CHAR(1)
);

CREATE TABLE PLAYERINFO 
(
  LEAGUE	CHAR(20) NOT NULL,
  ALIAS	CHAR(8),
  PLAYER_NAME	CHAR(10),
  PLAYER_NO	INTEGER,
  CURR_TEAM	CHAR(10),
  OTHER_TEAM	CHAR(10),
  PLAYER_POSITION	CHAR(2),
  FLAG	CHAR(1),
  ACT	CHAR(1),
  ISEQNO	INTEGER,
  ONFIELD	CHAR(1)
);

CREATE TABLE TEMPHLINFO 
(
  MATCH_CNT	INTEGER,
  ACT	CHAR(1),
  OLD_MD	CHAR(8),
  OLD_MT	CHAR(4),
  OLD_HOST	CHAR(8),
  OLD_GUEST	CHAR(8)
);

CREATE TABLE TEMPODDSINFO 
(
  MATCH_CNT	INTEGER,
  ACT	CHAR(1),
  OLD_MD	CHAR(8),
  OLD_MT	CHAR(4),
  OLD_HOST	CHAR(8),
  OLD_GUEST	CHAR(8),
  OLD_INTERVAL	INTEGER
);

CREATE TABLE TEMPOTHERODDSINFO 
(
  MATCH_CNT	INTEGER,
  ACT	CHAR(1),
  OLD_MD	CHAR(8),
  OLD_MT	CHAR(4),
  OLD_HOST	CHAR(8),
  OLD_GUEST	CHAR(8)
);