create table TIMEOFGAME_INFO
(
  IMATCH_CNT	INTEGER NOT NULL,
  STARTTIME		TIMESTAMP,
  CSTATUS			VARCHAR(1),
  CONSTRAINT PKTIMEOFGAME PRIMARY KEY (IMATCH_CNT)
);
grant all on TIMEOFGAME_INFO to public;
commit;