DROP TABLE "SYSMONIPMUXCFG";
commit;

CREATE TABLE "SYSMONIPMUXCFG" 
(
  "ISYSMON_NO" INTEGER NOT NULL,
  "CDISPLAY" VARCHAR(50) NOT NULL,
  "CCHANNEL_REF" VARCHAR(4),
  "CCHANNEL_IP"	VARCHAR(15),
  "CCHANNEL_PORT" VARCHAR(5),
  "COBJECT_URI"	VARCHAR(20),
  "CIPMUX_IP"	VARCHAR(15),
  "CIPMUX_PORT" VARCHAR(5),
  "IENABLED" INTEGER,
  "ISHOW_DETAILS" INTEGER,
CONSTRAINT "SYSMONIPMUXCFG_PK" PRIMARY KEY ("ISYSMON_NO")
);
commit;

INSERT INTO "SYSMONIPMUXCFG" ("ISYSMON_NO", "CDISPLAY", "CCHANNEL_REF", "CCHANNEL_IP", "CCHANNEL_PORT", "COBJECT_URI", "CIPMUX_IP", "CIPMUX_PORT", "IENABLED", "ISHOW_DETAILS") VALUES (1, 'Channel A', 'tcp', '127.0.0.1', '8801', 'IPmuxStatus', '128.128.2.30', '11000', 1, 0);
INSERT INTO "SYSMONIPMUXCFG" ("ISYSMON_NO", "CDISPLAY", "CCHANNEL_REF", "CCHANNEL_IP", "CCHANNEL_PORT", "COBJECT_URI", "CIPMUX_IP", "CIPMUX_PORT", "IENABLED", "ISHOW_DETAILS") VALUES (2, 'Channel B', 'tcp', '127.0.0.1', '8801', 'IPmuxStatus', '128.128.2.29', '11227', 1, 0);
commit;