INSERT INTO "SVCCFG" ("ISVC_NO", "CSVC_NAME", "CACCESS_RIGHT", "DEL_TYPE") VALUES (15, '足球1資訊', '011', 'W');
COMMIT;

INSERT INTO "ADMINSVCMAP" ("ISVC_NO", "IADMIN_NO", "LASTUPDATE") VALUES (15, 32, '2006/10/16 02:00:00');
INSERT INTO "ADMINSVCMAP" ("ISVC_NO", "IADMIN_NO", "LASTUPDATE") VALUES (15, 33, '2006/10/16 02:00:00');
INSERT INTO "ADMINSVCMAP" ("ISVC_NO", "IADMIN_NO", "LASTUPDATE") VALUES (15, 34, '2006/10/16 02:00:00');
COMMIT;



delete from ANALYSIS_BG_INFO;
delete from ANALYSIS_HISTORY_INFO;
delete from ANALYSIS_RECENT_INFO;
delete from ANALYSIS_REMARK_INFO;
delete from ANALYSIS_STAT_INFO;
commit;

select CACCESS_RIGHT, CSVC_NAME from SVCCFG where ISVC_NO=15 and DEL_TYPE='W'

select CCATEGORY, CPARAM, CCMD_TYPE, CDISPLAY from ADMINCFG where IADMIN_NO in (select IADMIN_NO from ADMINSVCMAP where ISVC_NO=15) AND (CCMD_TYPE='CLR_ALL' OR CCMD_TYPE='OTHODDS_ALLDEL') group by CCATEGORY, CDISPLAY, CPARAM, CCMD_TYPE order by CCATEGORY, IADMIN_NO


/* Backup */
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (2, 1, 'H', 'U', '英超', '保頓', 1, -1, -1);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (2, 2, 'H', 'U', '英超', '錫菲聯', 1, 1, 1);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (2, 3, 'H', 'U', '英超', '韋斯咸', 0, 2, 1);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (2, 4, 'H', 'U', '英超', '愛華頓', 1, 0, 3);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (2, 5, 'H', 'U', '英超', '車路士', 1, 0, 1);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (2, 6, 'H', 'U', '英超', '紐卡素', 0, 2, 0);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (2, 7, 'G', 'U', '英超', '樸茨茅', 0, -1, -1);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (2, 8, 'G', 'U', '英超', '保頓', 1, 0, 2);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (2, 9, 'G', 'U', '英超', '錫菲聯', 0, 2, 0);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (2, 10, 'G', 'U', '英超', '愛華頓', 0, 0, 2);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (2, 11, 'G', 'U', '英超', '曼聯', 1, 0, 1);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (2, 12, 'G', 'U', '英超', '富咸', 0, 0, 0);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (1, 1, 'H', 'U', '英超', '查爾頓', 1, -1, -1);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (1, 2, 'H', 'U', '英超', '維拉', 0, 1, 1);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (1, 3, 'H', 'U', '英超', '曼城', 1, 0, 1);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (1, 4, 'H', 'U', '英超', '米杜士', 0, 1, 1);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (1, 5, 'H', 'U', '英超', '曼聯', 1, 1, 0);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (1, 6, 'G', 'U', '英超', '米杜士', 0, -1, -1);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (1, 7, 'G', 'U', '英超', '利物浦', 0, 1, 1);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (1, 8, 'G', 'U', '英超', '熱刺', 1, 0, 2);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (1, 9, 'G', 'U', '英超', '富咸', 1, 0, 1);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (1, 10, 'G', 'U', '英超', '布力般', 0, 0, 0);
INSERT INTO "ANALYSIS_RECENT_INFO" ("IMATCH_CNT", "IREC", "CTEAMFLAG", "CACT", "CLEAGUEALIAS", "CCHALLENGER", "IMATCHSTATUS", "IHOSTSCORE", "IGUESTSCORE") VALUES (1, 11, 'G', 'U', '英超', '雷丁', 0, 1, 2);