CREATE GENERATOR LOG_BSKRANK_SEQ_GEN;
SET GENERATOR LOG_BSKRANK_SEQ_GEN TO 0;
COMMIT;

CREATE TABLE LOG_BSK_RANK 
(
  ISEQ_NO	INTEGER NOT NULL,
  TIMEFLAG	TIMESTAMP NOT NULL,
  IITEMSEQ_NO INTEGER,
  SECTION	VARCHAR(16) NOT NULL,
  TYPE_NAME	VARCHAR(16),
  ACT VARCHAR(1),
  RANKNO	INTEGER,
  PARAM_1	VARCHAR(16),
  PARAM_2	VARCHAR(16),
  PARAM_3	VARCHAR(16),
  PARAM_4	VARCHAR(16),
  PARAM_5	VARCHAR(16),
  BATCHJOB	VARCHAR(60),
CONSTRAINT LOG_BSK_RANK_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);

SET TERM !! ;
create trigger AUTO_LOG_BSKRANK_SEQ for LOG_BSK_RANK
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_BSKRANK_SEQ_GEN, 1);
end!!
SET TERM ;!!
commit;