CREATE GENERATOR LOG_BSKALLODDS_SEQ_GEN;
SET GENERATOR LOG_BSKALLODDS_SEQ_GEN TO 0;
COMMIT;

CREATE TABLE LOG_BSK_ALLODDS
(
  ISEQ_NO	INTEGER NOT NULL,
  TIMEFLAG	TIMESTAMP NOT NULL,
  Section	VARCHAR(8) NOT NULL,
  Act	VARCHAR(1),
  League	VARCHAR(20),
  Host	VARCHAR(16),
  Guest	VARCHAR(20),
  MatchDate	VARCHAR(8),
  MatchTime	VARCHAR(4),
  MatchField	VARCHAR(1),
  Handicap	VARCHAR(5),
  ScoreHandicap	  VARCHAR(5),
  SH_odds   VARCHAR(5),
  ScoreTarget  VARCHAR(5),
  ST_Odds   VARCHAR(5),
  WH_Odds   VARCHAR(5),
  WG_Odds   VARCHAR(5),
  Alert_Type   VARCHAR(1),
  BATCHJOB	VARCHAR(60),
CONSTRAINT LOG_BSK_ALLODDS_PK PRIMARY KEY (ISEQ_NO, TIMEFLAG)
);

SET TERM !! ;
create trigger AUTO_LOG_BSKALLODDS_SEQ for LOG_BSK_ALLODDS
before insert as
begin
new.ISEQ_NO = GEN_ID(LOG_BSKALLODDS_SEQ_GEN, 1);
end!!
SET TERM ;!!
commit;