CREATE TABLE PLAYERS_INFO 
(
  CTEAM_ID	VARCHAR(3) NOT NULL,
  IPLAYER_NO	INTEGER,
  IPOS	INTEGER,
  CCHI_NAME	VARCHAR(10) NOT NULL,
  CCOUNTRY	VARCHAR(10),
  IROSTER	INTEGER,
CONSTRAINT PLAYERS_PK PRIMARY KEY (CTEAM_ID, CCHI_NAME)
);