CREATE TABLE RANKPERSONAL_INFO 
(
  CLEAG_ID	VARCHAR(3) NOT NULL,
  CTEAM_ID	VARCHAR(3) NOT NULL,
  CCHI_NAME VARCHAR(10) NOT NULL,
  IRANK	INTEGER,
  CRANK_DATA	VARCHAR(5),
CONSTRAINT RKPERSONAL_PK PRIMARY KEY (CLEAG_ID, CTEAM_ID, CCHI_NAME)
);