DROP TABLE "SVCCFG";
COMMIT;

CREATE TABLE "SVCCFG" 
(
  "ISVC_NO"	INTEGER NOT NULL,
  "CSVC_NAME"	VARCHAR(50),
  "CACCESS_RIGHT"	VARCHAR(3),
  "DEL_TYPE"	VARCHAR(3),
CONSTRAINT "SVCCFG_PK" PRIMARY KEY ("ISVC_NO")
);
COMMIT;

INSERT INTO "SVCCFG" ("ISVC_NO", "CSVC_NAME", "CACCESS_RIGHT", "DEL_TYPE") VALUES (1, 'GOGO1 Sender', '011', 'P');
INSERT INTO "SVCCFG" ("ISVC_NO", "CSVC_NAME", "CACCESS_RIGHT", "DEL_TYPE") VALUES (2, 'GOGO2 Handler 1', '011', 'P');
INSERT INTO "SVCCFG" ("ISVC_NO", "CSVC_NAME", "CACCESS_RIGHT", "DEL_TYPE") VALUES (3, 'GOGO2 Handler 2', '011', 'P');
INSERT INTO "SVCCFG" ("ISVC_NO", "CSVC_NAME", "CACCESS_RIGHT", "DEL_TYPE") VALUES (4, '馬會 Sender', '011', 'P');
INSERT INTO "SVCCFG" ("ISVC_NO", "CSVC_NAME", "CACCESS_RIGHT", "DEL_TYPE") VALUES (5, '馬會 Handler 1', '011', 'P');
INSERT INTO "SVCCFG" ("ISVC_NO", "CSVC_NAME", "CACCESS_RIGHT", "DEL_TYPE") VALUES (6, '馬會 Handler 2', '011', 'P');
INSERT INTO "SVCCFG" ("ISVC_NO", "CSVC_NAME", "CACCESS_RIGHT", "DEL_TYPE") VALUES (7, 'GOGO 籃球', '011', 'P');
INSERT INTO "SVCCFG" ("ISVC_NO", "CSVC_NAME", "CACCESS_RIGHT", "DEL_TYPE") VALUES (8, '馬會 籃球', '011', 'P');
INSERT INTO "SVCCFG" ("ISVC_NO", "CSVC_NAME", "CACCESS_RIGHT", "DEL_TYPE") VALUES (10, 'Combo Soccer Goal', '011', 'P');
INSERT INTO "SVCCFG" ("ISVC_NO", "CSVC_NAME", "CACCESS_RIGHT", "DEL_TYPE") VALUES (11, 'Combo Soccer Misc', '011', 'P');
INSERT INTO "SVCCFG" ("ISVC_NO", "CSVC_NAME", "CACCESS_RIGHT", "DEL_TYPE") VALUES (13, 'Combo 籃球', '011', 'P');
INSERT INTO "SVCCFG" ("ISVC_NO", "CSVC_NAME", "CACCESS_RIGHT", "DEL_TYPE") VALUES (14, '足球2資訊', '011', 'W');
COMMIT;

INSERT INTO "ADMINCFG" ("IADMIN_NO", "CCATEGORY", "CDISPLAY", "CCMD_TYPE", "CPARAM") VALUES (123, '足球2', '比數詳情', 'CLR_ALL', 'RES');
COMMIT;

INSERT INTO "ADMINSVCMAP" ("ISVC_NO", "IADMIN_NO", "LASTUPDATE") VALUES (14, 115, '2006/09/26 02:00:00');
INSERT INTO "ADMINSVCMAP" ("ISVC_NO", "IADMIN_NO", "LASTUPDATE") VALUES (14, 117, '2006/09/26 02:00:00');
INSERT INTO "ADMINSVCMAP" ("ISVC_NO", "IADMIN_NO", "LASTUPDATE") VALUES (14, 123, '2006/09/26 02:00:00');
COMMIT;