ALTER TABLE "RESULTINFO"
ALTER COLUMN "HOST_PLAYERNO" TO "SENT_FLAG",
ALTER COLUMN "GUEST_PLAYERNO" TO "FGS_PLAYER_NO";

ALTER TABLE "RESULTINFO"
ALTER COLUMN SENT_FLAG TYPE CHAR(2),
ALTER COLUMN FGS_PLAYER_NO TYPE CHAR(3); 

ALTER TABLE "LOG_GOALDETAILS"
ADD FGS_PLAYER_NO VARCHAR(3);

ALTER TABLE "LOG_GOALDETAILS"
ALTER COLUMN FGS_PLAYER_NO POSITION 17;

ALTER TABLE "OTHRESULTINFO"
ALTER COLUMN "HOST_PLAYERNO" TO "SENT_FLAG",
ALTER COLUMN "GUEST_PLAYERNO" TO "FGS_PLAYER_NO";

ALTER TABLE "OTHRESULTINFO"
ALTER COLUMN SENT_FLAG TYPE CHAR(2),
ALTER COLUMN FGS_PLAYER_NO TYPE CHAR(3); 

/* Back forward */
ALTER TABLE "LOG_GOALDETAILS"
DROP FGS_PLAYER_NO;

ALTER TABLE "RESULTINFO"
ALTER COLUMN "SENT_FLAG" TO "HOST_PLAYERNO";
