CREATE TABLE "JCCOMBO_PLAYERS_INFO" 
(
  "TEAM_ID"	INTEGER NOT NULL,
  "IPLAYER_NO"	INTEGER,
  "IPOS"	INTEGER,
  "CPLAYER_NAME"	VARCHAR(10) NOT NULL,
  "CCOUNTRY"	VARCHAR(10),
  "IROSTER"	INTEGER,
  "CENGNAME"	VARCHAR(50),
CONSTRAINT "PKCOMBOPLAYER" PRIMARY KEY ("TEAM_ID", "CPLAYER_NAME")
);

ALTER TABLE LOG_ANALYSISPLAYERS
    ALTER COLUMN PLAYERNAME TYPE varchar(22);
