/*Last update on 14 April 2003*/
CREATE TABLE EMPTYMSG_CFG_INFO (IMSG_ID	INTEGER NOT NULL,CMSG_NAME	VARCHAR(10),CMSG_CONTENT	VARCHAR(100) NOT NULL,CONSTRAINT EMPTYMSGCFG_INFOPK PRIMARY KEY (IMSG_ID))
CREATE TABLE GOALMN_DETAILS (IMATCHNO	INTEGER NOT NULL,IHEADERID	INTEGER,IGPCNT	INTEGER,IPREVGPHDRID	INTEGER,INEXTGPHDRID	INTEGER,IBACKGPHDRID	INTEGER,ITOITEMHDRID	INTEGER,ISTARTITEMHDRID	INTEGER,IENDITEMHDRID	INTEGER,CDIRTY	VARCHAR(10),PRIMARY KEY (IMATCHNO))
CREATE TABLE GOAL_DETAILS (IMATCHNO	INTEGER NOT NULL,IHEADERID	INTEGER,IPREVGPHDRID	INTEGER,INEXTGPHDRID	INTEGER,ICHARTHDRID	INTEGER,CDIRTY	VARCHAR(10),PRIMARY KEY (IMATCHNO))
CREATE TABLE HKMAIN_DETAILS (IMATCHNO	INTEGER NOT NULL,CLEAGUE	VARCHAR(10),CHOST	VARCHAR(4),CGUEST	VARCHAR(4),IDATE	INTEGER,ITIME	INTEGER,CMATCH_FIELD	VARCHAR(1),IHANDICAP	INTEGER,CONSTRAINT HKMAIN_DETAILSPK PRIMARY KEY (IMATCHNO))
CREATE TABLE HKODDS_DETAILS (IMATCHNO	INTEGER NOT NULL,ISCORE_HANDICAP	VARCHAR(4),ISCORE_TARGET	VARCHAR(5),FSH_ODDS	VARCHAR(5),FST_ODDS	VARCHAR(5),FWH_ODDS	VARCHAR(5),FWG_ODDS	VARCHAR(5),IALERT	INTEGER,CTIMESTAMP	VARCHAR(16),CONSTRAINT HKODDS_DETAILSPK PRIMARY KEY (IMATCHNO))
CREATE TABLE HKRESULTMN_DETAILS (IMATCHNO	INTEGER NOT NULL,IHEADERID	INTEGER NOT NULL,IGPCNT	INTEGER,IPREVGPHDRID	INTEGER,INEXTGPHDRID	INTEGER,IBACKGPHDRID	INTEGER,ITOITEMHDRID	INTEGER,ISTARTITEMHDRID	INTEGER,IENDITEMHDRID	INTEGER,CDIRTY	VARCHAR(10),CONSTRAINT HKGOALMN_DETAILSPK PRIMARY KEY (IHEADERID))
CREATE TABLE HKRESULT_DETAILS (IMATCHNO	INTEGER NOT NULL,IHEADERID	INTEGER NOT NULL,IPREVGPHDRID	INTEGER,INEXTGPHDRID	INTEGER,ICHARTHDRID	INTEGER,CDIRTY	VARCHAR(10),CONSTRAINT HKGOAL_DETAILSPK PRIMARY KEY (IHEADERID))
CREATE TABLE HKSCOREDATA_DETAILS (IMATCHNO	INTEGER NOT NULL,ISECTIONNO	INTEGER NOT NULL,IHOSTSCORE	INTEGER,IGUESTSCORE	INTEGER,CONSTRAINT HKSCOREDATA_PK PRIMARY KEY (IMATCHNO, ISECTIONNO))
CREATE TABLE HKSCORE_DETAILS (IMATCHNO	INTEGER NOT NULL,CLV_STATUS	VARCHAR(6),CREMARKS	VARCHAR(50),IALERT	INTEGER,CTIMESTAMP	VARCHAR(16),CONSTRAINT HKSCORE_PK PRIMARY KEY (IMATCHNO))
CREATE TABLE IDMAP_INFO (CLEAG_ID	VARCHAR(3) NOT NULL,CTEAM_ID	VARCHAR(3) NOT NULL,CONSTRAINT IDMAP_INFOPK PRIMARY KEY (CLEAG_ID, CTEAM_ID))
CREATE TABLE JOB_QUEUE (IRECNO	INTEGER NOT NULL,IPRIORITY	INTEGER,CFILENAME	VARCHAR(50),PRIMARY KEY (IRECNO))
CREATE TABLE LEAGUE_INFO (CLEAG_ID	VARCHAR(3) NOT NULL,CLEAGUE	VARCHAR(18) NOT NULL,CALIAS	VARCHAR(10) NOT NULL,CORG	VARCHAR(10),CLEAGUETYPE	VARCHAR(1) NOT NULL,CONSTRAINT LEAGUE_INFOPK PRIMARY KEY (CLEAG_ID))
CREATE TABLE LOGIN_INFO (IUSER_ID	INTEGER NOT NULL,CUSERNAME	VARCHAR(20) NOT NULL,CPASSWD	VARCHAR(15) NOT NULL,CACCESS_RIGHT	VARCHAR(3),CUSER_GP	VARCHAR(10),CONSTRAINT LOGIN_INFOPK PRIMARY KEY (IUSER_ID),CONSTRAINT LOGIN_INFOUNICONST UNIQUE (CUSERNAME))
CREATE TABLE MAIN_DETAILS (IMATCHNO	INTEGER NOT NULL,CLEAGUE	VARCHAR(10),CHOST	VARCHAR(4),CGUEST	VARCHAR(4),IDATE	INTEGER,ITIME	INTEGER,CMATCH_FIELD	VARCHAR(1),IHANDICAP	INTEGER,CONSTRAINT MAIN_DETAILSPK PRIMARY KEY (IMATCHNO))
CREATE TABLE MANAGEMAP (MANAGEID	VARCHAR(2),MANAGENAME	VARCHAR(16))
CREATE TABLE MATCHMN_DETAILS (IMATCHNO	INTEGER NOT NULL,IHEADERID	INTEGER,IGPCNT	INTEGER,IPREVGPHDRID	INTEGER,INEXTGPHDRID	INTEGER,IBACKGPHDRID	INTEGER,ITOITEMHDRID	INTEGER,ISTARTITEMHDRID	INTEGER,IENDITEMHDRID	INTEGER,CDIRTY	VARCHAR(10),PRIMARY KEY (IMATCHNO))
CREATE TABLE MATCH_DETAILS (IMATCHNO	INTEGER NOT NULL,IHEADERID	INTEGER,IPREVGPHDRID	INTEGER,INEXTGPHDRID	INTEGER,ICHARTHDRID	INTEGER,CDIRTY	VARCHAR(10),PRIMARY KEY (IMATCHNO))
CREATE TABLE MSGTYPE_CFG (IRECNO	INTEGER NOT NULL,CMSGTYPE	VARCHAR(20),CPREFIX	VARCHAR(5),CCAPCODE	VARCHAR(7),CTONE	VARCHAR(1),IHDRIDSTART	INTEGER,IHDRIDEND	INTEGER,CSONGID	VARCHAR(4),IPRIORITY	INTEGER,PRIMARY KEY (IRECNO))
CREATE TABLE NBAGAME_INFO (IMATCH_COUNT	INTEGER NOT NULL,CLEAG	VARCHAR(18) NOT NULL,CHOST	VARCHAR(8) NOT NULL,CGUEST	VARCHAR(8) NOT NULL,ISEQ_NO	INTEGER,CACTION	VARCHAR(1),CMATCH_DATE	VARCHAR(8),CMATCH_TIME	VARCHAR(4),CMATCH_FIELD	VARCHAR(1),CHOST_HANDI	VARCHAR(1),CSCORE_HANDI	VARCHAR(4),CSH_ODDS	VARCHAR(6),CSCORE_TARGET	VARCHAR(5),CST_ODDS	VARCHAR(6),CWH_ODDS	VARCHAR(6),CWG_ODDS	VARCHAR(6),IALERT_TYRE	INTEGER,CSENT_FLAG	VARCHAR(1),CWEB_VIEW	VARCHAR(1),IINTERVAL	INTEGER,CONSTRAINT NBAGAME_INFOPK PRIMARY KEY (IMATCH_COUNT))
CREATE TABLE NBARESULT_INFO (IMATCH_COUNT	INTEGER NOT NULL,IMATCH_STATUS	INTEGER,IQUARTER1_HSCORE	INTEGER,IQUARTER1_GSCORE	INTEGER,IQUARTER2_HSCORE	INTEGER,IQUARTER2_GSCORE	INTEGER,IQUARTER3_HSCORE	INTEGER,IQUARTER3_GSCORE	INTEGER,IQUARTER4_HSCORE	INTEGER,IQUARTER4_GSCORE	INTEGER,IOT1_HSCORE	INTEGER,IOT1_GSCORE	INTEGER,IOT2_HSCORE	INTEGER,IOT2_GSCORE	INTEGER,IOT3_HSCORE	INTEGER,IOT3_GSCORE	INTEGER,IOT4_HSCORE	INTEGER,IOT4_GSCORE	INTEGER,IALERT_TYPE	INTEGER,CREMARKS	VARCHAR(20),CSONG_ID	VARCHAR(4),CSENT_FLAG	VARCHAR(1),CONSTRAINT NBARESULT_INFOPK PRIMARY KEY (IMATCH_COUNT))
CREATE TABLE ODDS_DETAILS (IMATCHNO	INTEGER NOT NULL,ISCORE_HANDICAP	VARCHAR(4),ISCORE_TARGET	VARCHAR(5),FSH_ODDS	VARCHAR(5),FST_ODDS	VARCHAR(5),FWH_ODDS	VARCHAR(5),FWG_ODDS	VARCHAR(5),IALERT	INTEGER,CTIMESTAMP	VARCHAR(16),CONSTRAINT ODDS_DETAILSPK PRIMARY KEY (IMATCHNO))
CREATE TABLE PLAYER_INFO (CPLAYER_ID	VARCHAR(3) NOT NULL,CPLAYER_NAME	VARCHAR(10) NOT NULL,CLEAG_ID	VARCHAR(3) NOT NULL,CTEAM_ID	VARCHAR(3) NOT NULL,CPLAYER_NO	VARCHAR(3),CPLAYER_COUNTRY	VARCHAR(10),CPLAYER_POSITION	VARCHAR(10),CONSTRAINT TABLE1PRIMARYKEY1 PRIMARY KEY (CPLAYER_ID))
CREATE TABLE RANKITEMDATA_DETAILS (IITEMNO	INTEGER NOT NULL,IRANKNO	INTEGER NOT NULL,CPARAM1	VARCHAR(8),CPARAM2	VARCHAR(8),CPARAM3	VARCHAR(8),CPARAM4	VARCHAR(8),CPARAM5	VARCHAR(8),PRIMARY KEY (IITEMNO, IRANKNO))
CREATE TABLE RANKITEM_DETAILS (IITEMNO	INTEGER NOT NULL,CTYPE	VARCHAR(15),CTIMESTAMP	VARCHAR(16),PRIMARY KEY (IITEMNO))
CREATE TABLE RANK_DETAILS (IITEMNO	INTEGER NOT NULL,IHEADERID	INTEGER,IPREVGPHDRID	INTEGER,INEXTGPHDRID	INTEGER,ICHARTHDRID	INTEGER,CDIRTY	VARCHAR(10),PRIMARY KEY (IITEMNO))
CREATE TABLE RANK_LEAGUE_INFO (CLEAG_ID	VARCHAR(3) NOT NULL,CTEAM_ID	VARCHAR(3) NOT NULL,CACTION	VARCHAR(1),IRANK	INTEGER,IWIN	INTEGER,ILOSS	INTEGER,ICONSECTIVE	INTEGER,ICONSECTIVE_TYPE	INTEGER,CONSTRAINT RANK_LEAGUE_INFOPRIMARYKEY1 PRIMARY KEY (CLEAG_ID, CTEAM_ID))
CREATE TABLE RANK_PERSONAL_INFO (IRANK_TYPE	INTEGER NOT NULL,CPLAYER_ID	VARCHAR(3) NOT NULL,IRANK	INTEGER,CRANK_DATA	VARCHAR(5))
CREATE TABLE SCOREDATA_DETAILS (IMATCHNO	INTEGER NOT NULL,ISECTIONNO	INTEGER NOT NULL,IHOSTSCORE	INTEGER,IGUESTSCORE	INTEGER,CONSTRAINT SCOREDATA_DETAILPK PRIMARY KEY (IMATCHNO, ISECTIONNO))
CREATE TABLE SCORE_DETAILS (IMATCHNO	INTEGER NOT NULL,CLV_STATUS	VARCHAR(6),CREMARKS	VARCHAR(50),IALERT	INTEGER,CTIMESTAMP	VARCHAR(16),CONSTRAINT SCORE_DETAILSPK PRIMARY KEY (IMATCHNO))
CREATE TABLE SELECTSTAUS (STATUSID	INTEGER,STATUSNAME	VARCHAR(8))
CREATE TABLE SONGINFO (SONG_ID	CHAR(4) NOT NULL,SONG_NAME	CHAR(25),CONSTRAINT SONGINFOPK PRIMARY KEY (SONG_ID))
CREATE TABLE TEAM_INFO (CTEAM_ID	VARCHAR(3) NOT NULL,CTEAM	VARCHAR(16) NOT NULL,CCOUNTRY	VARCHAR(8),CCITY	VARCHAR(12),CVENUE	VARCHAR(20),CCONTINENT	VARCHAR(12),CONSTRAINT TEAM_INFOPK PRIMARY KEY (CTEAM_ID))
CREATE TABLE USERPROFILE_INFO (IREC_NO	INTEGER NOT NULL,IUSER_ID	INTEGER NOT NULL,CLEAG_ID	VARCHAR(3) NOT NULL,CONSTRAINT USERPROFILE_INFOPK PRIMARY KEY (IREC_NO))


CREATE INDEX GOALMN_DETAILSIDX ON GOALMN_DETAILS(IMATCHNO, IHEADERID)
CREATE INDEX GOAL_DETAILSIDX ON GOAL_DETAILS(IMATCHNO, IHEADERID)
CREATE INDEX MAIN_DETAILSIDX1 ON MAIN_DETAILS(IMATCHNO, CGUEST)
CREATE INDEX MAIN_DETAILSIDX2 ON MAIN_DETAILS(CLEAGUE)
CREATE INDEX MATCHMN_DETAILSIDX ON MATCHMN_DETAILS(IMATCHNO, IHEADERID)
CREATE INDEX MATCH_DETAILSIDX ON MATCH_DETAILS(IMATCHNO, IHEADERID)
CREATE INDEX MSGTYPE_CFGIDX ON MSGTYPE_CFG(IRECNO)
CREATE INDEX RANKITEMDATA_IDX ON RANKITEMDATA_DETAILS(IITEMNO, IRANKNO)
CREATE INDEX RANKITEM_IDX ON RANKITEM_DETAILS(IITEMNO)
CREATE INDEX RANK_DETAILSIDX ON RANK_DETAILS(IITEMNO)
CREATE INDEX SCOREDATA_IDX ON SCOREDATA_DETAILS(IMATCHNO, ISECTIONNO)
CREATE INDEX SCORE_DETAILSIDX ON SCORE_DETAILS(IMATCHNO)


/* Grant Roles for this database */


/* Grant permissions for this database */

GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON EMPTYMSG_CFG_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON GOALMN_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON GOAL_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON HKMAIN_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON HKODDS_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON HKRESULTMN_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON HKRESULT_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON HKSCOREDATA_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON HKSCORE_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON IDMAP_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON JOB_QUEUE TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON LEAGUE_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON LOGIN_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON MAIN_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON MATCHMN_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON MATCH_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON MSGTYPE_CFG TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON NBAGAME_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON NBARESULT_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ODDS_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RANKITEMDATA_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RANKITEM_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RANK_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RANK_LEAGUE_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RANK_PERSONAL_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SCOREDATA_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SCORE_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON USERPROFILE_INFO TO PUBLIC;
