/*Last update on 24 April 2003*/
CREATE TABLE ANALYSISINFO (MATCH_CNT INTEGER NOT NULL,MATCH_VENUE CHAR(20),WEATHER_TEMP CHAR(8),WEATHER_STATUS CHAR(1),ACT CHAR(1),FLAG CHAR(1),HIS_LEAG0 CHAR(8),HIS_DATE0 CHAR(8),HIS_MATCH_STATUS0 CHAR(1),HIS_HSCR0 CHAR(2),HIS_GSCR0 CHAR(2),HIS_LEAG1 CHAR(8),HIS_DATE1 CHAR(8),HIS_MATCH_STATUS1 CHAR(1),HIS_HSCR1 CHAR(2),HIS_GSCR1 CHAR(2),HIS_LEAG2 CHAR(8),HIS_DATE2 CHAR(8),HIS_MATCH_STATUS2 CHAR(1),HIS_HSCR2 CHAR(2),HIS_GSCR2 CHAR(2),REMARKS CHAR(750))
CREATE TABLE ANALYSISMENU_DETAILS (IHEADER_ID INTEGER NOT NULL,CLEAGUE VARCHAR(20) NOT NULL,CHOST VARCHAR(18),CGUEST VARCHAR(18),IGPCNT INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,IBACKGPHDRID INTEGER,ITOITEMHDRID INTEGER,ISTARTITEMHDRID INTEGER,IENDITEMHDRID INTEGER,CDIRTY VARCHAR(10),IREC_NO INTEGER default 0 NOT NULL)
CREATE TABLE ANALYSIS_DETAILS (IHEADER_ID INTEGER NOT NULL,CHOST VARCHAR(10) NOT NULL,CGUEST VARCHAR(10) NOT NULL,CLEAGUEALIAS VARCHAR(8) NOT NULL,CLEAGUE VARCHAR(18) NOT NULL,IMATCH_DATE INTEGER NOT NULL,IMATCH_TIME INTEGER NOT NULL,CMATCH_FIELD VARCHAR(1),CHANDI VARCHAR(1),CMATCH_VENUE VARCHAR(18),CHOST_COUNTRY VARCHAR(10),CHOST_CITY VARCHAR(10),CHOST_CONTINENT VARCHAR(10),CGUEST_COUNTRY VARCHAR(10),CGUEST_CITY VARCHAR(10),CGUEST_CONTINENT VARCHAR(10),CWEA_TEMP VARCHAR(6),CWEA_SIT VARCHAR(6),CHIS_DATE0 INTEGER,CHIS_LEAG0 VARCHAR(8),CHIS_STATUS0 VARCHAR(2),CHIS_HSCR0 INTEGER,CHIS_GSCR0 INTEGER,CHIS_DATE1 INTEGER,CHIS_LEAG1 VARCHAR(8),CHIS_STATUS1 VARCHAR(2),CHIS_HSCR1 INTEGER,CHIS_GSCR1 INTEGER,CHIS_DATE2 INTEGER,CHIS_LEAG2 VARCHAR(8),CHIS_STATUS2 VARCHAR(2),CHIS_HSCR2 INTEGER,CHIS_GSCR2 INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,CDIRTY VARCHAR(10),CACTION VARCHAR(10),CTIMESTAMP VARCHAR(16),CREMARK VARCHAR(750),IREC_NO INTEGER default 0 NOT NULL)
CREATE TABLE ANALYSIS_RECENT_INFO (  IMATCH_CNT	INTEGER NOT NULL,  IREC	INTEGER NOT NULL,  CTEAMFLAG	VARCHAR(1),  CACT	VARCHAR(1),  CLEAGUEALIAS	VARCHAR(8),  CCHALLENGER	VARCHAR(8),  IMATCHSTATUS	INTEGER,  IHOSTSCORE	INTEGER,  IGUESTSCORE	INTEGER,CONSTRAINT PKANLYRECENT PRIMARY KEY (IMATCH_CNT, IREC))
CREATE TABLE ANALYSIS_STAT_INFO (  IMATCH_CNT	INTEGER NOT NULL,  CACT	VARCHAR(1),  IHOSTWIN	INTEGER,  IHOSTDRAW	INTEGER,  IHOSTLOSS	INTEGER,  IGUESTWIN	INTEGER,  IGUESTDRAW	INTEGER,  IGUESTLOSS	INTEGER,CONSTRAINT PKANLYSTAT PRIMARY KEY (IMATCH_CNT))
CREATE TABLE ANAMN_DETAILS (IANA_ID INTEGER NOT NULL,IHEADER_ID INTEGER,IGPCNT INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,IBACKGPHDRID INTEGER,ITOITEMHDRID INTEGER,ISTARTITEMHDRID INTEGER,IENDITEMHDRID INTEGER,ICHARTHDRID INTEGER,PRIMARY KEY (IANA_ID))
CREATE TABLE ANA_DETAILS (IANA_ID INTEGER NOT NULL,CHOST_ROOT VARCHAR(20),CGUEST_ROOT VARCHAR(20),CVENUE VARCHAR(20),CTEMP VARCHAR(20),CWEATHER VARCHAR(20),IHEADER_ID INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,ICHARTHDRID INTEGER,PRIMARY KEY (IANA_ID))
CREATE TABLE ANA_HIST_DETAILS (IANA_ID INTEGER NOT NULL,ISEQ_NO INTEGER NOT NULL,CLEAGUEALIAS VARCHAR(10),IDATE INTEGER,CDESC VARCHAR(4),IHOST_SCORE INTEGER,IGUEST_SCORE INTEGER,PRIMARY KEY (IANA_ID, ISEQ_NO))
CREATE TABLE ANA_MAIN_DETAILS (IANA_ID INTEGER NOT NULL,CLEAGUE VARCHAR(10) NOT NULL,CHOST VARCHAR(10) NOT NULL,CGUEST VARCHAR(10) NOT NULL,IDATE INTEGER,CMATCHFIELD VARCHAR(4),CHANDICAPE VARCHAR(4),CMAIN_DIRTY VARCHAR(10),CDATA_DIRTY VARCHAR(10),CHIST_DIRTY VARCHAR(10),CPLAYER_DIRTY VARCHAR(10),CRMK_DIRTY VARCHAR(10),PRIMARY KEY (IANA_ID))
CREATE TABLE ANA_PLAYER_DETAILS (IANA_ID INTEGER NOT NULL,ISEQ_NO INTEGER NOT NULL,CTYPE VARCHAR(20),CPOS VARCHAR(20),CPLAYER VARCHAR(20),INO INTEGER,PRIMARY KEY (IANA_ID, ISEQ_NO))
CREATE TABLE ANA_RMK_DETAILS (IANA_ID	INTEGER NOT NULL,CREMARKS	VARCHAR(350),PRIMARY KEY (IANA_ID))
CREATE TABLE ASIAODDSMATCH_INFO (IMATCH_ID INTEGER NOT NULL,CHOST VARCHAR(8) NOT NULL,CGUEST VARCHAR(8) NOT NULL,CLEAGUE VARCHAR(10) NOT NULL,CLEAGUEALIAS VARCHAR(6),CCOMPANY VARCHAR(8) NOT NULL,MATCHDATETIME TIMESTAMP,CMATCH_FIELD VARCHAR(1),CHOSTRANK VARCHAR(5),CGUESTRANK VARCHAR(5),LASTUPDATE TIMESTAMP,CONSTRAINT ASIAODDS_PK PRIMARY KEY (IMATCH_ID),CONSTRAINT ASIAODDS_UNIQUE UNIQUE (CHOST, CGUEST, CLEAGUE, CCOMPANY))
CREATE TABLE CNANALYSIS_INFO (IREC_NO INTEGER NOT NULL,CISSUE_NO VARCHAR(8) NOT NULL,ISEQ_NO INTEGER NOT NULL,IHOSTWIN INTEGER,IHOSTDRAW INTEGER,IHOSTLOSS INTEGER,IGUSETWIN INTEGER,IGUSETDRAW INTEGER,IGUSETLOSS INTEGER,CHOSTODDSWIN VARCHAR(5),CHOSTODDSLOSS VARCHAR(5),CHOSTODDSDRAW VARCHAR(5))
CREATE TABLE CNBET_INFO (IREC_NO INTEGER NOT NULL,ISEQ_NO INTEGER NOT NULL,CISSUE_NO VARCHAR(8) NOT NULL,CLEAGUE CHAR(14),CHOST CHAR(10),CGUEST CHAR(10),IMATCHDATE INTEGER,FLAG CHAR(1),CANASENDFLAG VARCHAR(1))
CREATE TABLE CNPAY_INFO (IREC_NO INTEGER NOT NULL,CISSUE_NO VARCHAR(8) NOT NULL,IFISRTPAY INTEGER,ISECONDPAY INTEGER,ITHIRDPAY INTEGER)
CREATE TABLE CNRESULT_INFO (IREC_NO INTEGER NOT NULL,CISSUE_NO VARCHAR(8) NOT NULL,ISEQ_NO INTEGER NOT NULL,ISTARTPAYDATE CHAR(8),IENDPAYDATE CHAR(8),ISCORE INTEGER,CLUCKYDRAW CHAR(1))
CREATE TABLE CN_ANAMN_DETAILS (IREC_NO INTEGER default 0 NOT NULL,IHEADER_ID INTEGER,CLEAGUE VARCHAR(20),CHOST VARCHAR(10),CGUEST VARCHAR(10),IGPCNT INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,IBACKGPHDRID INTEGER,ITOITEMHDRID INTEGER,ISTARTITEMHDRID INTEGER,IENDITEMHDRID INTEGER,CDIRTY VARCHAR(10),CTIMESTAMP VARCHAR(16))
CREATE TABLE CN_ANA_DETAILS (IREC_NO INTEGER default 0 NOT NULL,IHEADER_ID INTEGER,CLEAGUE VARCHAR(10),CLEAGUEALIAS VARCHAR(10),CHOST VARCHAR(10),CGUEST VARCHAR(10),IHOST_WIN_PT INTEGER,IHOST_EQ_PT INTEGER,IHOST_LOST_PT INTEGER,IGUEST_WIN_PT INTEGER,IGUEST_EQ_PT INTEGER,IGUEST_LOST_PT INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,ICHARTHDRID INTEGER,CDIRTY VARCHAR(10),CTIMESTAMP VARCHAR(16),CHOST_EODDS_WIN VARCHAR(5),CHOST_EODDS_LOST VARCHAR(5),CHOST_EODDS_EQ VARCHAR(5),IISSUE_NO INTEGER)
CREATE TABLE CN_DVDMN_DETAILS (IREC_NO INTEGER default 0 NOT NULL,IHEADER_ID INTEGER,CGAME VARCHAR(20),IISSUE_NO INTEGER,IGPCNT INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,IBACKGPHDRID INTEGER,ITOITEMHDRID INTEGER,ISTARTITEMHDRID INTEGER,IENDITEMHDRID INTEGER,CDIRTY VARCHAR(10),CTIMESTAMP VARCHAR(16))
CREATE TABLE CN_DVD_DETAILS (IREC_NO INTEGER default 0 NOT NULL,CGAME VARCHAR(20),IISSUE_NO INTEGER,IHEADER_ID INTEGER,IFST_PRIZE INTEGER,ISEC_PRIZE INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,ICHARTHDRID INTEGER,CDIRTY VARCHAR(10),CTIMESTAMP VARCHAR(16),ITHD_PRIZE INTEGER)
CREATE TABLE CN_MATCHDATA_DETAILS (IREC_NO INTEGER default 0 NOT NULL,IMATCHHDRID INTEGER,IMATCH_NO INTEGER,CLEAGUEALIAS VARCHAR(10),CHOST VARCHAR(10),CGUEST VARCHAR(10),IDATE INTEGER)
CREATE TABLE CN_MATCHMN_DETAILS (IREC_NO INTEGER default 0 NOT NULL,IHEADER_ID INTEGER,CGAME VARCHAR(20),IISSUE_NO INTEGER,IGPCNT INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,IBACKGPHDRID INTEGER,ITOITEMHDRID INTEGER,ISTARTITEMHDRID INTEGER,IENDITEMHDRID INTEGER,CDIRTY VARCHAR(10),CTIMESTAMP VARCHAR(16))
CREATE TABLE CN_MATCH_DETAILS (IREC_NO INTEGER default 0 NOT NULL,CGAME VARCHAR(20),IISSUE_NO INTEGER,IHEADER_ID INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,ICHARTHDRID INTEGER,CDIRTY VARCHAR(10),CTIMESTAMP VARCHAR(16))
CREATE TABLE CN_RESDATA_DETAILS (IREC_NO INTEGER default 0 NOT NULL,IRESHDRID INTEGER,IMATCH_NO INTEGER,CHOST VARCHAR(10),IRESULT INTEGER,IDRAWRES INTEGER)
CREATE TABLE CN_RESMN_DETAILS (IREC_NO INTEGER default 0 NOT NULL,IHEADER_ID INTEGER,CGAME VARCHAR(20),IISSUE_NO INTEGER,IGPCNT INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,IBACKGPHDRID INTEGER,ITOITEMHDRID INTEGER,ISTARTITEMHDRID INTEGER,IENDITEMHDRID INTEGER,CDIRTY VARCHAR(10),CTIMESTAMP VARCHAR(16))
CREATE TABLE CN_RES_DETAILS (IREC_NO INTEGER default 0 NOT NULL,CGAME VARCHAR(20),IISSUE_NO INTEGER,IHEADER_ID INTEGER,IDRAW_DATE INTEGER,ICLOSE_DATE INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,ICHARTHDRID INTEGER,CDIRTY VARCHAR(10),CTIMESTAMP VARCHAR(16))
CREATE TABLE COM_QUERY (IREC_NO INTEGER NOT NULL,ISENT INTEGER default 0 NOT NULL,CQUERY VARCHAR(1200) NOT NULL,PRIMARY KEY (IREC_NO))
CREATE TABLE COM_QUEUE (IREC_NO INTEGER NOT NULL,IPRIORITY INTEGER NOT NULL,ISENT INTEGER default 0 NOT NULL,CHDRID VARCHAR(4),CQUERY VARCHAR(800) NOT NULL)
CREATE TABLE DISCARD_BY_ST (IRECNO INTEGER,CPARAM1 VARCHAR(20),CPARAM2 VARCHAR(20))
CREATE TABLE DISCARD_BY_TDL (IRECNO INTEGER,CPARAM1 VARCHAR(20),CPARAM2 VARCHAR(20))
CREATE TABLE FOREODDS_DETAILS (IHEADER_ID INTEGER NOT NULL,CHOST VARCHAR(18) NOT NULL,CGUEST VARCHAR(18) NOT NULL,CLEAGUEALIAS VARCHAR(10) NOT NULL,CLEAGUE VARCHAR(20) NOT NULL,IMATCH_DATE INTEGER NOT NULL,IMATCH_TIME INTEGER NOT NULL,CMATCH_FIELD VARCHAR(1) NOT NULL,CFSTHANDI VARCHAR(20),CFSTSCOREHANDI VARCHAR(10),CFSTODDSVALUE VARCHAR(10),IFSTDATE INTEGER,CSECHANDI VARCHAR(20),CSECSCOREHANDI VARCHAR(10),CSECODDSVALUE VARCHAR(10),ISECDATE INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,ICHARTHDRID INTEGER,CLGDIRTY VARCHAR(10),CMSGDIRTY VARCHAR(10),CACTION VARCHAR(10),CTIMESTAMP VARCHAR(16),IREC_NO INTEGER default 0 NOT NULL,PRIMARY KEY (IREC_NO))
CREATE TABLE GAMEINFO (LEAGUE CHAR(6) NOT NULL,HOST CHAR(8) NOT NULL,GUEST CHAR(8) NOT NULL,ACT CHAR(1),MATCH_ID CHAR(3) NOT NULL,MATCHDATE CHAR(8),MATCHTIME CHAR(4),FIELD CHAR(1),HOST_HANDI CHAR(1),T_HANDI1 CHAR(3),T_HANDI2 CHAR(3),M_HANDI1 CHAR(3),M_HANDI2 CHAR(3),ODDSTYPE1 CHAR(2),TY1_ODDS CHAR(5),TY1_STATUS CHAR(1),ODDSTYPE2 CHAR(2),TY2_ODDS CHAR(5),TY2_STATUS CHAR(1),EU_W_ODDS CHAR(4),EU_L_ODDS CHAR(4),EU_D_ODDS CHAR(4),ALERT_TH CHAR(1),ALERT_MH CHAR(1),ALERT_TO CHAR(1),ALERT_MO CHAR(1),ALERT_EO CHAR(1),FLAG CHAR(1),LEAGLONG CHAR(24),MATCH_CNT INTEGER,WEBACT CHAR(1),INTERVAL INTEGER,CONSTRAINT PKGAME PRIMARY KEY (LEAGUE, HOST, GUEST))
CREATE TABLE GENINFO (MSGID INTEGER NOT NULL,INFODATE CHAR(8),INFOTIME CHAR(4),ACT CHAR(1),FLAG CHAR(1),TITLE CHAR(40),CONTENT CHAR(240),PRIMARY KEY (MSGID))
CREATE TABLE GOALINFO (COUNTER INTEGER NOT NULL,MATCH_CNT INTEGER NOT NULL,ORDER_ID CHAR(2),ACT CHAR(1),WEBACT CHAR(1),H_SCR CHAR(2),H_SCR_V CHAR(1),G_SCR CHAR(2),G_SCR_V CHAR(1),FLAG CHAR(1),SONG_ID CHAR(4),GOAL_ALERT CHAR(1),STATUS CHAR(1),MATCHDATE CHAR(8),MATCHTIME CHAR(4),REMARK CHAR(30),CONSTRAINT GOALKEY PRIMARY KEY (COUNTER))
CREATE TABLE GOAL_DETAILS (IHEADER_ID INTEGER NOT NULL,CLEAGUE VARCHAR(20) NOT NULL,CHOST VARCHAR(18) NOT NULL,CGUEST VARCHAR(18) NOT NULL,IH_GOAL INTEGER,IG_GOAL INTEGER,IH_CONFIRM INTEGER,IG_CONFIRM INTEGER,IGPCNT INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,IBACKGPHDRID INTEGER,ITOITEMHDRID INTEGER,ISTARTITEMHDRID INTEGER,IENDITEMHDRID INTEGER,IALERT INTEGER,ISONGID INTEGER,CSTATUS VARCHAR(6),CDIRTY VARCHAR(10),CTIMESTAMP VARCHAR(16),CCOMMENT VARCHAR(20),IREC_NO INTEGER default 0 NOT NULL)
CREATE TABLE HALFODDS_DETAILS (IHEADER_ID INTEGER NOT NULL,CHOST VARCHAR(18) NOT NULL,CGUEST VARCHAR(18) NOT NULL,CLEAGUEALIAS VARCHAR(6) NOT NULL,CLEAGUE VARCHAR(18) NOT NULL,CMATCH_FIELD VARCHAR(1),IHANDICAP INTEGER,CHANDI VARCHAR(10),CODDSSTATUS VARCHAR(10),CODDSVAL VARCHAR(10),IH_GOAL INTEGER,IG_GOAL INTEGER,IALERT INTEGER,ISEQNO INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,CDIRTY VARCHAR(10),CACTION VARCHAR(10),CTIMESTAMP VARCHAR(16),IREC_NO INTEGER default 0 NOT NULL)
CREATE TABLE HISTORYINFO (LEAGUE CHAR(20),ALIAS CHAR(8),TEAM CHAR(10),MATCH CHAR(12),WIN INTEGER,LOSS INTEGER,DRAW INTEGER,SCORE_NO INTEGER,MISS_NO INTEGER,SHOOTER0 CHAR(10),SCORE0 INTEGER,SHOOTER1 CHAR(10),SCORE1 INTEGER,SHOOTER2 CHAR(10),SCORE2 INTEGER,GOALKEEPER CHAR(10),MISS INTEGER,FLAG CHAR(1),ACT CHAR(1))
CREATE TABLE HISTORY_DETAILS (IHEADER_ID INTEGER,CLEAGUEALIAS VARCHAR(10),IRANK INTEGER,CTEAM VARCHAR(8),CREGION VARCHAR(10),CMATCH VARCHAR(10),IWIN INTEGER,ILOSS INTEGER,IDRAW INTEGER,IGOAL INTEGER,IMISS INTEGER,CSHOOTER_NAME0 VARCHAR(10),ISHOOTER_SCORE0 INTEGER,CSHOOTER_NAME1 VARCHAR(10),ISHOOTER_SCORE1 INTEGER,CSHOOTER_NAME2 VARCHAR(10),ISHOOTER_SCORE2 INTEGER,CKEEPER_NAME VARCHAR(10),IKEEPER_SCORE INTEGER,ISEQ_NO INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,ICHARTHDRID INTEGER,CLGDIRTY VARCHAR(10),CMSGDIRTY VARCHAR(10),ITEAM_NO INTEGER,CTIMESTAMP VARCHAR(14),CRANKINFO VARCHAR(12),IREC_NO INTEGER default 0 NOT NULL)
CREATE TABLE HKGOAL_DETAILS (IHEADER_ID INTEGER NOT NULL,CLEAGUE VARCHAR(20) NOT NULL,CHOST VARCHAR(18) NOT NULL,CGUEST VARCHAR(18) NOT NULL,IH_GOAL INTEGER,IG_GOAL INTEGER,IH_CONFIRM INTEGER,IG_CONFIRM INTEGER,IGPCNT INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,IBACKGPHDRID INTEGER,ITOITEMHDRID INTEGER,ISTARTITEMHDRID INTEGER,IENDITEMHDRID INTEGER,IALERT INTEGER,ISONGID INTEGER,CSTATUS VARCHAR(6),CDIRTY VARCHAR(10),CTIMESTAMP VARCHAR(16),CCOMMENT VARCHAR(20),IREC_NO INTEGER default 0 NOT NULL)
CREATE TABLE HKODDMENU_DETAILS (IHEADER_ID INTEGER NOT NULL,CLEAGUE VARCHAR(20) NOT NULL,CHOST VARCHAR(18),CGUEST VARCHAR(18),IGPCNT INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,IBACKGPHDRID INTEGER,ITOITEMHDRID INTEGER,ISTARTITEMHDRID INTEGER,IENDITEMHDRID INTEGER,CDIRTY VARCHAR(10),IREC_NO INTEGER default 0 NOT NULL)
CREATE TABLE HKODDS_DETAILS (IHEADER_ID	INTEGER NOT NULL,CHOST	VARCHAR(18) NOT NULL,CGUEST	VARCHAR(18) NOT NULL,CLEAGUEALIAS	VARCHAR(10) NOT NULL,CLEAGUE	VARCHAR(20) NOT NULL,IMATCH_DATE	INTEGER NOT NULL,IMATCH_TIME	INTEGER NOT NULL,ISEQ_NO	INTEGER NOT NULL,CMATCH_FIELD	VARCHAR(1) NOT NULL,CHANDI	VARCHAR(1) NOT NULL,CT_HANDIOWNER	VARCHAR(6),CT_HANDI	VARCHAR(20),CM_HANDIOWNER	VARCHAR(6),CM_HANDI	VARCHAR(20),CT_LIVEODDS	VARCHAR(10),CT_ODDS	VARCHAR(20),CM_LIVEODDS	VARCHAR(10),CM_ODDS	VARCHAR(20),CE_ODDS1	VARCHAR(20),CE_ODDS2	VARCHAR(20),IALERT	INTEGER,IPREVGPHDRID	INTEGER,INEXTGPHDRID	INTEGER,ICHARTHDRID	INTEGER,IINTERVAL	INTEGER,CDIRTY	VARCHAR(10),CACTION	VARCHAR(10),CTIMESTAMP	VARCHAR(16),CCHART_TIMESTAMP	VARCHAR(16),CTREND	VARCHAR(6),IREC_NO	INTEGER default 0 NOT NULL)
CREATE TABLE HKRES_DETAILS (IHEADER_ID	INTEGER NOT NULL,CLEAGUE	VARCHAR(20) NOT NULL,CHOST	VARCHAR(18) NOT NULL,CGUEST	VARCHAR(18) NOT NULL,CSTATUS	VARCHAR(2),IMATCH_DATE	INTEGER,IMATCH_TIME	INTEGER,IPREVGPHDRID	INTEGER,INEXTGPHDRID	INTEGER,CDIRTY	VARCHAR(10),CMATCH_FIELD	VARCHAR(1),IALERT	INTEGER,CTIMESTAMP	VARCHAR(16),CPKFIRST	VARCHAR(10),IREC_NO	INTEGER default 0 NOT NULL)
CREATE TABLE HKSCORE_DETAILS (CLEAGUE	VARCHAR(20) NOT NULL,CHOST	VARCHAR(18) NOT NULL,CGUEST	VARCHAR(18) NOT NULL,CSTATUS	VARCHAR(2),ITIME	INTEGER,CGOAL	VARCHAR(4),CPLAYER	VARCHAR(30),CREDFLAG	VARCHAR(2),ISEQ_NO	INTEGER,CHOSTPK	VARCHAR(30),CGUESTPK	VARCHAR(30),IREC_NO	INTEGER default 0 NOT NULL)
CREATE TABLE HLINFO (LEAGUE	CHAR(6) NOT NULL,HOST	CHAR(8) NOT NULL,GUEST	CHAR(8) NOT NULL,ACT	CHAR(1),MATCH_CNT	INTEGER NOT NULL,MATCH_ID	CHAR(3) NOT NULL,MATCHDATE	CHAR(8),MATCHTIME	CHAR(4),MSTATUS	CHAR(1),FIELD	CHAR(1),HOST_HANDI	CHAR(1),FENZHONG	CHAR(4),HANDI1	CHAR(3),HANDI2	CHAR(3),ODDS	CHAR(5),OSTATUS	CHAR(1),ALERT_H	CHAR(1),LEAGLONG	CHAR(24),ORDER_ID	CHAR(2),H_SCR	CHAR(2),G_SCR	CHAR(2),FLAG	CHAR(1),SONG_ID	CHAR(4),HALFLIVE	CHAR(1))
CREATE TABLE ID_INFO (LEAG_ID	CHAR(3) NOT NULL,TEAM_ID	CHAR(3) NOT NULL,CDUMMY	VARCHAR(1))
CREATE TABLE INFO_DETAILS (IHEADER_ID	INTEGER NOT NULL,IPREVGPHDRID	INTEGER,INEXTGPHDRID	INTEGER,IMSGID	INTEGER NOT NULL,IDATE	INTEGER,ITIME	INTEGER,CTITLE	VARCHAR(40),CCONTENT	VARCHAR(300),CDIRTY	VARCHAR(10),IREC_NO	INTEGER default 0 NOT NULL)
CREATE TABLE LEAGINFO (LEAG_ID	CHAR(3) NOT NULL,LEAGNAME	CHAR(40),ORG	CHAR(40),ALIAS	CHAR(8),LEAGUETYPE	CHAR(1),LEAG_ORDER	INTEGER,PRIMARY KEY (LEAG_ID))
CREATE TABLE LEAGRANKINFO (LEAG_ID	CHAR(2),RANK	INTEGER,TEAM	CHAR(10),SCORE	INTEGER,FLAG	CHAR(1),GAMES	INTEGER)
CREATE TABLE LIST_DETAILS (IHEADER_ID	INTEGER,CPLAYER	VARCHAR(20),CPOS	VARCHAR(10),CCLUB	VARCHAR(10),ISEQNO	INTEGER,IONFIELD	INTEGER,IPLAYERNO	INTEGER,IREC_NO	INTEGER default 0 NOT NULL)
CREATE TABLE LOGININFO (USER_ID	INTEGER NOT NULL,USERNAME	CHAR(20) NOT NULL,PWD	CHAR(15),ACCESS_RIGHT	CHAR(3),DESCRIPTION	VARCHAR(20),UNIQUE (USERNAME),PRIMARY KEY (USER_ID))
CREATE TABLE LVODDS_DETAILS (IHEADER_ID	INTEGER NOT NULL,CHOST	VARCHAR(18) NOT NULL,CGUEST	VARCHAR(18) NOT NULL,CLEAGUEALIAS	VARCHAR(6) NOT NULL,CLEAGUE	VARCHAR(18) NOT NULL,CMATCH_FIELD	VARCHAR(1),IHANDICAP	INTEGER,CHANDI	VARCHAR(10),CODDSSTATUS	VARCHAR(10),CODDSVAL	VARCHAR(10),IH_GOAL	INTEGER,IG_GOAL	INTEGER,ICURRTM	INTEGER,IALERT	INTEGER,ISEQNO	INTEGER,IPREVGPHDRID	INTEGER,INEXTGPHDRID	INTEGER,CDIRTY	VARCHAR(10),CACTION	VARCHAR(10),CTIMESTAMP	VARCHAR(16),IREC_NO	INTEGER default 0 NOT NULL)
CREATE TABLE MCHANDICAP_MAP (CMCHANDICAP	VARCHAR(15) NOT NULL,CHANDICAP	VARCHAR(8) NOT NULL,LASTUPDATE	TIMESTAMP,CONSTRAINT MCHANDICAPMAP_PK PRIMARY KEY (CMCHANDICAP, CHANDICAP))
CREATE TABLE MCLEAG_MAP (CMCLEAGUE	VARCHAR(20) NOT NULL,CLEAGUE	VARCHAR(10) NOT NULL,CLEAGUEALIAS	VARCHAR(6) NOT NULL,LASTUPDATE	TIMESTAMP,CONSTRAINT MCLEAGMAP_PK PRIMARY KEY (CMCLEAGUE, CLEAGUE, CLEAGUEALIAS))
CREATE TABLE MCTEAM_MAP (CMCTEAM	VARCHAR(20) NOT NULL,CTEAM	VARCHAR(8) NOT NULL,LASTUPDATE	TIMESTAMP,CONSTRAINT MCTEAMMAP_PK PRIMARY KEY (CMCTEAM, CTEAM))
CREATE TABLE NAMELIST_DETAILS (IHEADER_ID	INTEGER,CLEAGUEALIAS	VARCHAR(10),ILEAGUECNT	INTEGER,CTEAM	VARCHAR(10),ITEAMCNT	INTEGER,CLGDIRTY	VARCHAR(10),CMSGDIRTY	VARCHAR(10),CTIMESTAMP	VARCHAR(16),IREC_NO	INTEGER default 0 NOT NULL)
CREATE TABLE NEWSINFO (IMSG_ID	INTEGER NOT NULL,CACT	VARCHAR(1),IAPP_ID	INTEGER,CNEWSDATE	VARCHAR(8),CNEWSTIME	VARCHAR(4),CMESSAGE	VARCHAR(400),FLAG	VARCHAR(1))
CREATE TABLE NEWS_CFG (ISEQNO	INTEGER NOT NULL,CAPPTYPE	VARCHAR(20),CINFOTYPE	VARCHAR(10),IHDRIDSTART	INTEGER,IHDRIDEND	INTEGER,CTONE	VARCHAR(1),CCAPCODE	VARCHAR(10),PRIMARY KEY (ISEQNO))
CREATE TABLE NEWS_DETAILS (IHEADER_ID	INTEGER,IPREVGPHDRID	INTEGER,INEXTGPHDRID	INTEGER,CDIRTY	VARCHAR(10),CTIMESTAMP	VARCHAR(16),IAPPID	INTEGER,IMSGID	INTEGER,IDATE	INTEGER,ITIME	INTEGER,CCONTENT	VARCHAR(450),IREC_NO	INTEGER default 0 NOT NULL)
CREATE TABLE ODDMENU_DETAILS (IHEADER_ID	INTEGER NOT NULL,CLEAGUE	VARCHAR(20) NOT NULL,CHOST	VARCHAR(18),CGUEST	VARCHAR(18),IGPCNT	INTEGER,IPREVGPHDRID	INTEGER,INEXTGPHDRID	INTEGER,IBACKGPHDRID	INTEGER,ITOITEMHDRID	INTEGER,ISTARTITEMHDRID	INTEGER,IENDITEMHDRID	INTEGER,CDIRTY	VARCHAR(10),IREC_NO	INTEGER default 0 NOT NULL)
CREATE TABLE ODDSHISTORY (LEAGUE	CHAR(20) NOT NULL,HOST	CHAR(18) NOT NULL,GUEST	CHAR(18) NOT NULL,T_ODDS	FLOAT,T_HANDI	CHAR(10),CTIMESTAMP	CHAR(14),IREC_NO	INTEGER default 0 NOT NULL)
CREATE TABLE ODDSHISTORYBAK (LEAGUE	CHAR(20) NOT NULL,HOST	CHAR(18) NOT NULL,GUEST	CHAR(18) NOT NULL,T_ODDS	FLOAT,T_HANDI	CHAR(10),CTIMESTAMP	CHAR(14),IREC_NO	INTEGER default 0 NOT NULL)
CREATE TABLE ODDS_DETAILS (IHEADER_ID	INTEGER NOT NULL,CHOST	VARCHAR(18) NOT NULL,CGUEST	VARCHAR(18) NOT NULL,CLEAGUEALIAS	VARCHAR(10) NOT NULL,CLEAGUE	VARCHAR(20) NOT NULL,IMATCH_DATE	INTEGER NOT NULL,IMATCH_TIME	INTEGER NOT NULL,ISEQ_NO	INTEGER NOT NULL,CMATCH_FIELD	VARCHAR(1) NOT NULL,CHANDI	VARCHAR(1) NOT NULL,CT_HANDIOWNER	VARCHAR(6),CT_HANDI	VARCHAR(20),CM_HANDIOWNER	VARCHAR(6),CM_HANDI	VARCHAR(20),CT_LIVEODDS	VARCHAR(10),CT_ODDS	VARCHAR(20),CM_LIVEODDS	VARCHAR(10),CM_ODDS	VARCHAR(20),CE_ODDS1	VARCHAR(20),CE_ODDS2	VARCHAR(20),IALERT	INTEGER,IPREVGPHDRID	INTEGER,INEXTGPHDRID	INTEGER,ICHARTHDRID	INTEGER,IINTERVAL	INTEGER,CDIRTY	VARCHAR(10),CACTION	VARCHAR(10),CTIMESTAMP	VARCHAR(16),CCHART_TIMESTAMP	VARCHAR(16),CTREND	VARCHAR(6),IREC_NO	INTEGER default 0 NOT NULL)
CREATE TABLE OTHERODDSINFO (COMPANY	CHAR(10) NOT NULL,LEAGUE	CHAR(24) NOT NULL,ALIAS	CHAR(6) NOT NULL,HOST	CHAR(8) NOT NULL,GUEST	CHAR(8) NOT NULL,MATCH_CNT	INTEGER,ACT	CHAR(1),MATCHDATE	CHAR(8),MATCHTIME	CHAR(4),FIELD	CHAR(1),HOST_HANDI	CHAR(1),HANDICAP1	CHAR(3),HANDICAP2	CHAR(3),ODDS_UP	CHAR(5),ODDS_DOWN	CHAR(5),EU_ODDS_WIN	CHAR(4),EU_ODDS_LOSS	CHAR(4),EU_ODDS_DRAW	CHAR(4),ALERT	CHAR(1),FLAG	CHAR(1),WEBACT	CHAR(1),MATCH_ID	CHAR(3),STATUS	CHAR(1),CONSTRAINT PKOTHERODDS PRIMARY KEY (COMPANY, LEAGUE, HOST, GUEST))
CREATE TABLE OTHERRESINFO (LEAGUE	CHAR(20) NOT NULL,HOST	CHAR(8) NOT NULL,GUEST	CHAR(8) NOT NULL,MATCHDATE	CHAR(8),MATCHTIME	CHAR(4),STATUS	CHAR(1),ACT	CHAR(1),H_SCORE	CHAR(2),G_SCORE	CHAR(2),FLAG	CHAR(1),CSEND	VARCHAR(1),CONSTRAINT PKOTHER PRIMARY KEY (LEAGUE, HOST, GUEST))
CREATE TABLE OTHGOAL_DETAILS (IHEADER_ID INTEGER NOT NULL,CLEAGUE VARCHAR(20) NOT NULL,CLEAGUEALIAS VARCHAR(10) NOT NULL,CHOST VARCHAR(18) NOT NULL,CGUEST VARCHAR(18) NOT NULL,IMATCHDATE INTEGER,IMATCHTIME INTEGER,IH_GOAL INTEGER,IG_GOAL INTEGER,IPREVGPHDRID INTEGER,INEXTGPHDRID INTEGER,CSTATUS VARCHAR(6),ILGSEQNO INTEGER,IMSGSEQNO INTEGER,CLGDIRTY VARCHAR(10),CMSGDIRTY VARCHAR(10),CTIMESTAMP VARCHAR(16),IREC_NO INTEGER default 0 NOT NULL,IALERT INTEGER default 0)
CREATE TABLE OTHODDS_CFG (ISEQNO	INTEGER NOT NULL,CCOMPANY	VARCHAR(10),IHDRIDSTART	INTEGER,IHDRIDEND	INTEGER,IMENUIDSTART	INTEGER,IMENUIDEND	INTEGER,IBACKID	INTEGER,CFOOTNOTE	VARCHAR(100),PRIMARY KEY (ISEQNO))
CREATE TABLE OTHODDS_DETAILS (IHEADER_ID	INTEGER NOT NULL,CCOMPANY	VARCHAR(10) NOT NULL,CHOST	VARCHAR(18) NOT NULL,CGUEST	VARCHAR(18) NOT NULL,CLEAGUEALIAS	VARCHAR(10) NOT NULL,CLEAGUE	VARCHAR(20) NOT NULL,IMATCH_DATE	INTEGER NOT NULL,IMATCH_TIME	INTEGER NOT NULL,CMATCH_FIELD	VARCHAR(1) NOT NULL,IHOSTHANDI	INTEGER,CSCOREHANDI	VARCHAR(10),CODDSUP	VARCHAR(10),CODDSDN	VARCHAR(10),CEUODDS1	VARCHAR(10),CEUODDS2	VARCHAR(10),IALERT	INTEGER,IPREVGPHDRID	INTEGER,INEXTGPHDRID	INTEGER,ICHARTHDRID	INTEGER,CLGDIRTY	VARCHAR(10),CMSGDIRTY	VARCHAR(10),CACTION	VARCHAR(10),CTIMESTAMP	VARCHAR(16),IREC_NO	INTEGER default 0 NOT NULL,CLIVESTATUS	VARCHAR(10))
CREATE TABLE PENDINGFILE (FILE_NAME	VARCHAR(85),STATUS	VARCHAR(5))
CREATE TABLE PLACE_DETAILS (IRACENO	INTEGER,IRACESEQNO	INTEGER,IFSTPLACE	INTEGER,ISECPLACE	INTEGER,ITHDPLACE	INTEGER,IFRPLACE	INTEGER,CSTATUS	VARCHAR(10),IREC_NO	INTEGER default 0 NOT NULL)
CREATE TABLE PLAYERINFO (LEAGUE	CHAR(20) NOT NULL,ALIAS	CHAR(8),PLAYER_NAME	CHAR(10),PLAYER_NO	INTEGER,CURR_TEAM	CHAR(10),OTHER_TEAM	CHAR(10),PLAYER_POSITION	CHAR(2),FLAG	CHAR(1),ACT	CHAR(1),ISEQNO	INTEGER,ONFIELD	CHAR(1))
CREATE TABLE PRIORITY_CFG (IPRIORITY	INTEGER NOT NULL,CFILE_NAME	VARCHAR(85),CCLASS	VARCHAR(50),PRIMARY KEY (IPRIORITY))
CREATE TABLE RACECLASSINFO (CLASS	CHAR(20) NOT NULL,PRIMARY KEY (CLASS))
CREATE TABLE RACEINFO (IRACE_NO	INTEGER NOT NULL,CRACEDATE	CHAR(8),CRACETIME	CHAR(4),CRACETRACK	CHAR(8),CCLASS	CHAR(20),CRACELENGTH	CHAR(5),CRACESTATUS	CHAR(10),PRIMARY KEY (IRACE_NO))
CREATE TABLE RACEPLACEINFO (IPLACE_NO	INTEGER NOT NULL,IRACE_NO	INTEGER NOT NULL,CFIRST	CHAR(2),CSECOND	CHAR(2),CTHIRD	CHAR(2),CFOURTH	CHAR(2),CALERT	CHAR(1),CRACESTATUS	CHAR(10),CONSTRAINT PKPLACE PRIMARY KEY (IPLACE_NO, IRACE_NO))
CREATE TABLE RACEPLACE_DETAILS (IHEADER_ID	INTEGER,IRACEDATE	INTEGER,IRACETIME	INTEGER,CRACETRACK	VARCHAR(50),IRACENO	INTEGER,CRACECLASS	VARCHAR(50),CRACELENGTH	VARCHAR(20),IRACEALERT	INTEGER,ISEQNO	INTEGER,CDIRTY	VARCHAR(10),CTIMESTAMP	VARCHAR(16),IREC_NO	INTEGER default 0 NOT NULL)
CREATE TABLE RANK_DETAILS (IHEADER_ID	INTEGER,CLEAGUEALIAS	VARCHAR(10),IRANK	INTEGER,CTEAM	VARCHAR(14),ISCORE	INTEGER,IEVENTCNT	INTEGER,ISEQ_NO	INTEGER,IPREVGPHDRID	INTEGER,INEXTGPHDRID	INTEGER,ICHARTHDRID	INTEGER,CLGDIRTY	VARCHAR(10),CMSGDIRTY	VARCHAR(10),CTIMESTAMP	VARCHAR(16),IREC_NO	INTEGER default 0 NOT NULL,CUPDATEDATE	VARCHAR(10))
CREATE TABLE RANK_WCUP (ISEQNO	INTEGER,CLEAGUEALIAS	VARCHAR(10),ICASENO	INTEGER)
CREATE TABLE REP_MAPCAPCODE (IREC_NO	INTEGER NOT NULL,ISRC_NO	INTEGER NOT NULL,ITG_NO	INTEGER NOT NULL,CDESC	VARCHAR(50))
CREATE TABLE REP_SRCCAPCODE (IREC_NO	INTEGER NOT NULL,ISRC_NO	INTEGER NOT NULL,CPREFIX	VARCHAR(10),CCAPCODE	VARCHAR(10),CTONE	VARCHAR(1))
CREATE TABLE REP_TGCAPCODE (IREC_NO	INTEGER NOT NULL,ITG_NO	INTEGER NOT NULL,CPREFIX	VARCHAR(10),CCAPCODE	VARCHAR(10),CTONE	VARCHAR(1))
CREATE TABLE RESULTINFO (RESULT_ID	INTEGER NOT NULL,MATCH_CNT	INTEGER,LEAGUE	CHAR(24),ACT	CHAR(1),MATCHSTATE	CHAR(1),RES_FLAG	CHAR(1),RES_PERIOD	CHAR(2),RES_TIME	CHAR(3),H_SCR	CHAR(2),G_SCR	CHAR(2),FLAG	CHAR(1),ALERT	CHAR(1),PLAYER	CHAR(20),HOST_PLAYER	CHAR(15),HOST_PLAYERNO	CHAR(2),GUEST_PLAYER	CHAR(15),GUEST_PLAYERNO	CHAR(2),HOSTPK	CHAR(30),GUESTPK	CHAR(30))
CREATE TABLE RES_DETAILS (IHEADER_ID	INTEGER NOT NULL,CLEAGUE	VARCHAR(20) NOT NULL,CHOST	VARCHAR(18) NOT NULL,CGUEST	VARCHAR(18) NOT NULL,CSTATUS	VARCHAR(2),IMATCH_DATE	INTEGER,IMATCH_TIME	INTEGER,IPREVGPHDRID	INTEGER,INEXTGPHDRID	INTEGER,CDIRTY	VARCHAR(10),CMATCH_FIELD	VARCHAR(1),IALERT	INTEGER,CTIMESTAMP	VARCHAR(16),CPKFIRST	VARCHAR(10),IREC_NO	INTEGER default 0 NOT NULL)
CREATE TABLE SCHEDULEINFO (MSGID	INTEGER,MSGTYPE	CHAR(10),MSGCONTENT	CHAR(100))
CREATE TABLE SCH_DETAILS (CTYPE	VARCHAR(20),CCONTENT	VARCHAR(100),CTIMESTAMP	VARCHAR(16),IREC_NO	INTEGER default 0 NOT NULL)
CREATE TABLE SCORE_DETAILS (CLEAGUE	VARCHAR(20) NOT NULL,CHOST	VARCHAR(18) NOT NULL,CGUEST	VARCHAR(18) NOT NULL,CSTATUS	VARCHAR(2),ITIME	INTEGER,CGOAL	VARCHAR(4),CPLAYER	VARCHAR(30),CREDFLAG	VARCHAR(2),ISEQ_NO	INTEGER,CHOSTPK	VARCHAR(30),CGUESTPK	VARCHAR(30),IREC_NO	INTEGER default 0 NOT NULL)
CREATE TABLE SELFWIN_INFO (IMATCH_ID	INTEGER NOT NULL,CEWINODDS	VARCHAR(5),CEDRAWODDS	VARCHAR(5),CELOSSODDS	VARCHAR(5),LASTUPDATE	TIMESTAMP,CONSTRAINT SELFWIN_PK PRIMARY KEY (IMATCH_ID))
CREATE TABLE SONGINFO (SONG_ID	CHAR(4) NOT NULL,SONG_NAME	CHAR(25),CONSTRAINT SONGKEY PRIMARY KEY (SONG_ID))
CREATE TABLE TEAMINFO (TEAM_ID	CHAR(3) NOT NULL,TEAMNAME	CHAR(40),COUNTRY	CHAR(15),CITY	CHAR(15),VENUE	CHAR(20),CONTINENT	CHAR(8),PRIMARY KEY (TEAM_ID))
CREATE TABLE TEMPHLINFO (MATCH_CNT	INTEGER,ACT	CHAR(1),OLD_MD	CHAR(8),OLD_MT	CHAR(4),OLD_HOST	CHAR(8),OLD_GUEST	CHAR(8))
CREATE TABLE TEMPODDSINFO (MATCH_CNT	INTEGER,ACT	CHAR(1),OLD_MD	CHAR(8),OLD_MT	CHAR(4),OLD_HOST	CHAR(8),OLD_GUEST	CHAR(8),OLD_INTERVAL	INTEGER)
CREATE TABLE TEMPOTHERODDSINFO (MATCH_CNT	INTEGER,ACT	CHAR(1),OLD_MD	CHAR(8),OLD_MT	CHAR(4),OLD_HOST	CHAR(8),OLD_GUEST	CHAR(8))
CREATE TABLE TXCODE_TBL (IREC_NO	INTEGER NOT NULL,CHKBIG	VARCHAR(20),CHKCNS	VARCHAR(20),CCNBIG	VARCHAR(20),CCNCNS	VARCHAR(20),CDESC	VARCHAR(20))
CREATE TABLE USERPROFILE_INFO (IREC_NO	INTEGER NOT NULL,IUSER_ID	INTEGER,CLEAG_ID	VARCHAR(3),PRIMARY KEY (IREC_NO))
CREATE TABLE WINODDS_INFO (IMATCH_ID	INTEGER NOT NULL,CSCOREHANDI	VARCHAR(10),CHOSTODDS	VARCHAR(5),CGUESTODDS	VARCHAR(5),LASTUPDATE	TIMESTAMP,CONSTRAINT WINODDS_PK PRIMARY KEY (IMATCH_ID))
CREATE TABLE WPOOL_DETAILS (CCONTENT	VARCHAR(400),CTIMESTAMP	VARCHAR(16))
CREATE TABLE OTHERREGION_CFG (IREGION_ID INTEGER NOT NULL, CREGION VARCHAR(10) NOT NULL, CTOTAL_ODDS VARCHAR(5), LASTUPDATE TIMESTAMP, CONSTRAINT PKREGIONID PRIMARY KEY (IREGION_ID),  CONSTRAINT REGION_UNIQUE UNIQUE (CREGION))
CREATE TABLE STAT_MAIN_DETAILS(  ISTAT_ID	INTEGER NOT NULL,  CLEAGUE	VARCHAR(10) NOT NULL,  CHOST	VARCHAR(10) NOT NULL,  CGUEST	VARCHAR(10) NOT NULL,  PRIMARY KEY (ISTAT_ID))
CREATE TABLE STATMN_DETAILS(  ISTAT_ID	INTEGER NOT NULL,  IHEADER_ID	INTEGER,  IGPCNT	INTEGER,  IPREVGPHDRID	INTEGER,  INEXTGPHDRID	INTEGER,  IBACKGPHDRID	INTEGER,  ITOITEMHDRID	INTEGER,  ISTARTITEMHDRID	INTEGER,  IENDITEMHDRID	INTEGER,  ICHARTHDRID	INTEGER,  CDIRTY	VARCHAR(10),  PRIMARY KEY (ISTAT_ID))
CREATE TABLE STAT_DETAILS(  ISTAT_ID	INTEGER NOT NULL,  IHOST_WIN_PER	INTEGER,  IHOST_EQ_PER	INTEGER,  IHOST_LOST_PER	INTEGER,  IGUEST_WIN_PER	INTEGER,  IGUEST_EQ_PER	INTEGER,  IGUEST_LOST_PER	INTEGER,  IHEADER_ID	INTEGER,  IPREVGPHDRID	INTEGER,  INEXTGPHDRID	INTEGER,  ICHARTHDRID	INTEGER,  CDIRTY	VARCHAR(10),  PRIMARY KEY (ISTAT_ID))
CREATE TABLE RECENT_MAIN_DETAILS(  IRECENT_ID	INTEGER NOT NULL,  CLEAGUE	VARCHAR(10) NOT NULL,  CMATCH_FIELD	VARCHAR(5) NOT NULL,  CHOST	VARCHAR(10) NOT NULL,  CGUEST	VARCHAR(10) NOT NULL, PRIMARY KEY (IRECENT_ID))
CREATE TABLE RECENTMN_DETAILS(  IRECENT_ID	INTEGER NOT NULL,  IPREVORNEXT	INTEGER NOT NULL,  IHEADER_ID	INTEGER,  IGPCNT	INTEGER,  IPREVGPHDRID	INTEGER,  INEXTGPHDRID	INTEGER,  IBACKGPHDRID	INTEGER,  ITOITEMHDRID	INTEGER,  ISTARTITEMHDRID	INTEGER,  IENDITEMHDRID	INTEGER,  ICHARTHDRID	INTEGER,  CDIRTY	VARCHAR(10), PRIMARY KEY (IRECENT_ID, IPREVORNEXT))
CREATE TABLE RECENT_DETAILS(  IRECENT_ID	INTEGER NOT NULL,  IPREVORNEXT	INTEGER NOT NULL,  IHEADER_ID	INTEGER,  IPREVGPHDRID	INTEGER,  INEXTGPHDRID	INTEGER,  ICHARTHDRID	INTEGER,  CDIRTY	VARCHAR(10), PRIMARY KEY (IRECENT_ID, IPREVORNEXT))
CREATE TABLE RECENTDATA_DETAILS(  IRECENT_ID	INTEGER NOT NULL,  IPREVORNEXT	INTEGER NOT NULL,  ISEQ_NO	INTEGER NOT NULL,  CLEAGUEALIAS	VARCHAR(10),  CTEAM	VARCHAR(10),  CMATCH_FIELD	VARCHAR(5),  IHOST_SCORE	INTEGER,  IGUEST_SCORE	INTEGER, PRIMARY KEY (IRECENT_ID, IPREVORNEXT, ISEQ_NO))
CREATE TABLE PLAYERS_INFO (CTEAM_ID VARCHAR(3) NOT NULL, IPLAYER_NO INTEGER, IPOS INTEGER, CPLAYER_NAME VARCHAR(10) NOT NULL, CCOUNTRY VARCHAR(10), IROSTER INTEGER, CENGNAME	VARCHAR(50), CONSTRAINT PKPLAYER PRIMARY KEY (CTEAM_ID, CPLAYER_NAME))
CREATE TABLE ANALYSIS_HISTORY_INFO (IMATCH_CNT INTEGER NOT NULL, IREC INTEGER NOT NULL, CACT VARCHAR(1), CLEAGUEALIAS VARCHAR(8), IMATCHMONTH INTEGER, IMATCHYEAR INTEGER, IMATCHSTATUS INTEGER, IHOSTSCORE INTEGER, IGUESTSCORE INTEGER, CONSTRAINT PKANLYHISTORY PRIMARY KEY (IMATCH_CNT, IREC))
CREATE TABLE ANALYSIS_REMARK_INFO (IMATCH_CNT INTEGER NOT NULL, CACT VARCHAR(1), CREMARKS VARCHAR(300), CONSTRAINT PKANLYREMARK PRIMARY KEY (IMATCH_CNT))
CREATE TABLE ANALYSIS_BG_INFO (IMATCH_CNT INTEGER NOT NULL, CMATCH_VENUE VARCHAR(20), CTEMPERATURE VARCHAR(8), IWEATHER_STATUS	INTEGER, CACT VARCHAR(1), IFLAG_HISTORY INTEGER, IFLAG_PLAYERS INTEGER, IFLAG_REMARK INTEGER, CONSTRAINT PKANLYBG PRIMARY KEY (IMATCH_CNT))
CREATE TABLE TIMEOFGAME_INFO (IMATCH_CNT INTEGER NOT NULL, STARTTIME TIMESTAMP, CSTATUS VARCHAR(1), CONSTRAINT PKTIMEOFGAME PRIMARY KEY (IMATCH_CNT))

CREATE INDEX IRECX ON ANALYSIS_HISTORY_INFO(IREC)
CREATE INDEX ANAMNDETAILS1 ON ANAMN_DETAILS(IHEADER_ID)
CREATE INDEX ANADETAILS1 ON ANA_DETAILS(IHEADER_ID)
CREATE INDEX ANAHIST1 ON ANA_HIST_DETAILS(IANA_ID, ISEQ_NO)
CREATE INDEX ANAMAINIDX1 ON ANA_MAIN_DETAILS(IANA_ID)
CREATE INDEX ANAMAINIDX2 ON ANA_MAIN_DETAILS(CLEAGUE, CHOST, CGUEST)
CREATE INDEX ANAPLY1 ON ANA_PLAYER_DETAILS(IANA_ID)
CREATE INDEX ANARMK1 ON ANA_RMK_DETAILS(IANA_ID)
CREATE INDEX CNRESMN ON CN_RESMN_DETAILS(IREC_NO)
CREATE INDEX CNRES ON CN_RES_DETAILS(IREC_NO)
CREATE INDEX IRECNO_CQYX ON COM_QUERY(IREC_NO)
CREATE INDEX GAME_MATCHDATEX ON GAMEINFO(MATCHDATE)
CREATE INDEX GAME_MATCHIDX ON GAMEINFO(MATCH_ID)
CREATE INDEX GAME_MATCHTIMEX ON GAMEINFO(MATCHTIME)
CREATE INDEX MATCH_DATEX ON GOALINFO(MATCHDATE)
CREATE INDEX MATCH_TIMEX ON GOALINFO(MATCHTIME)
CREATE INDEX ORDER_IDX ON GOALINFO(ORDER_ID)
CREATE INDEX GOAL_DETAILSIDX1 ON GOAL_DETAILS(IHEADER_ID)
CREATE INDEX GOAL_DETAILSIDX2 ON GOAL_DETAILS(CDIRTY)
CREATE INDEX GOAL_DETAILSIDX3 ON GOAL_DETAILS(CLEAGUE)
CREATE INDEX GOAL_DETAILSIDX4 ON GOAL_DETAILS(CLEAGUE, CHOST, CGUEST)
CREATE INDEX LEAG_IDX ON LEAGINFO(LEAG_ID)
CREATE INDEX LEAG_ORDERX ON LEAGINFO(LEAG_ORDER)
CREATE INDEX MCHANDICAP_IDX ON MCHANDICAP_MAP(CHANDICAP)
CREATE INDEX MCALIAS_IDX ON MCLEAG_MAP(CLEAGUEALIAS)
CREATE INDEX MCLEAG_IDX ON MCLEAG_MAP(CLEAGUE)
CREATE INDEX MCTEAM_IDX ON MCTEAM_MAP(CTEAM)
CREATE INDEX ISEQNO_NFG ON NEWS_CFG(ISEQNO)
CREATE INDEX IGP_OHX ON ODDSHISTORY(LEAGUE, HOST, GUEST)
CREATE INDEX IPOSX ON PLAYERS_INFO(IPOS)
CREATE INDEX TEAM_IDX ON TEAMINFO(TEAM_ID)
CREATE INDEX TEAM_NAMEX ON TEAMINFO(TEAMNAME)

CREATE GENERATOR MCID_GEN;
SET TERM ^ ;


/* Triggers only will work for SQL triggers */

CREATE TRIGGER AUTOINC_MCID FOR ASIAODDSMATCH_INFO 
ACTIVE BEFORE INSERT POSITION 0
as
begin
new.IMATCH_ID = GEN_ID(MCID_GEN, 1)
end
 ^

COMMIT WORK ^
SET TERM ;^

/* Grant Roles for this database */


/* Grant permissions for this database */

GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ANALYSISINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ANALYSISMENU_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ANALYSIS_BG_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ANALYSIS_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ANALYSIS_HISTORY_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ANALYSIS_REMARK_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ANAMN_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ANA_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ANA_HIST_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ANA_MAIN_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ANA_PLAYER_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ANA_RMK_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ASIAODDSMATCH_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON CNANALYSIS_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON CNBET_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON CNPAY_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON CNRESULT_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON CN_ANAMN_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON CN_ANA_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON CN_DVDMN_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON CN_DVD_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON CN_MATCHDATA_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON CN_MATCHMN_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON CN_MATCH_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON CN_RESDATA_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON CN_RESMN_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON CN_RES_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON COM_QUERY TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON COM_QUEUE TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON DISCARD_BY_ST TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON DISCARD_BY_TDL TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON FOREODDS_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON GAMEINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON GENINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON GOALINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON GOAL_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON HALFODDS_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON HISTORYINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON HISTORY_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON HKGOAL_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON HKODDMENU_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON HKODDS_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON HKRES_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON HKSCORE_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON HLINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ID_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON INFO_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON LEAGINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON LEAGRANKINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON LIST_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON LOGININFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON LVODDS_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON MCHANDICAP_MAP TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON MCLEAG_MAP TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON MCTEAM_MAP TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON NAMELIST_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON NEWSINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON NEWS_CFG TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON NEWS_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ODDMENU_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ODDSHISTORY TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ODDSHISTORYBAK TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ODDS_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON OTHERODDSINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON OTHERRESINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON OTHGOAL_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON OTHODDS_CFG TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON OTHODDS_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON PENDINGFILE TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON PLACE_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON PLAYERINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON PLAYERS_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON PRIORITY_CFG TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RACECLASSINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RACEINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RACEPLACEINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RACEPLACE_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RANK_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RANK_WCUP TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON REP_MAPCAPCODE TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON REP_SRCCAPCODE TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON REP_TGCAPCODE TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RESULTINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RES_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SCHEDULEINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SCH_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SCORE_DETAILS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SELFWIN_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SONGINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON TEAMINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON TEMPHLINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON TEMPODDSINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON TEMPOTHERODDSINFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON TXCODE_TBL TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON USERPROFILE_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON WINODDS_INFO TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON WPOOL_DETAILS TO PUBLIC;
grant all on STAT_MAIN_DETAILS to public;
grant all on STATMN_DETAILS to public;
grant all on STAT_DETAILS to public;
grant all on RECENT_MAIN_DETAILS to public;
grant all on RECENTMN_DETAILS to public;
grant all on RECENT_DETAILS to public;
grant all on RECENTDATA_DETAILS to public;
grant all on analysis_stat_info to public;
grant all on analysis_recent_info to public;