DROP TABLE "LOG_OTHERSOCCER_LIVEGOAL";
COMMIT;
/*CREATE GENERATOR "LOG_OTHSGOAL_SEQ_GEN";*/

/* Table: LOG_OTHERSOCCER_LIVEGOAL, Owner: SYSDBA */

CREATE TABLE "LOG_OTHERSOCCER_LIVEGOAL" 
(
  "ISEQ_NO"	INTEGER NOT NULL,
  "TIMEFLAG"	TIMESTAMP NOT NULL,
  "SECTION"	VARCHAR(10) NOT NULL,
  "LEAGUE"	VARCHAR(20) NOT NULL,
  "HOST"	VARCHAR(8) NOT NULL,
  "GUEST"	VARCHAR(8) NOT NULL,
  "ACT"	VARCHAR(1),
  "MATCHDATE"	VARCHAR(8),
  "MATCHTIME"	VARCHAR(4),
  "MATCHFIELD"	VARCHAR(1),
  "H_GOAL"	INTEGER,
  "G_GOAL"	INTEGER,
  "H_CONFIRM"	INTEGER,
  "G_CONFIRM"	INTEGER,
  "SONGID"	VARCHAR(4),
  "ALERT"	INTEGER,
  "STATUS"	VARCHAR(4),
  "COMMENT"	VARCHAR(20),
  "TIMEOFGAME"	INTEGER,
  "BATCHJOB"	VARCHAR(60),
CONSTRAINT "LOG_OTHSLVGOAL_PK" PRIMARY KEY ("ISEQ_NO", "TIMEFLAG")
);
SET TERM ^ ;


/* Triggers only will work for SQL triggers */

CREATE TRIGGER "AUTO_LOG_OTHSGOAL_SEQ" FOR "LOG_OTHERSOCCER_LIVEGOAL" 
ACTIVE BEFORE INSERT POSITION 0
as
begin
new.ISEQ_NO = GEN_ID(LOG_OTHSGOAL_SEQ_GEN, 1);
end
 ^

COMMIT WORK ^
SET TERM ;^

/* Table: TIMEOFOTHERGAME_INFO, Owner: SYSDBA */

CREATE TABLE "TIMEOFOTHERGAME_INFO" 
(
  "IMATCH_CNT"	INTEGER NOT NULL,
  "STARTTIME"	TIMESTAMP,
  "CSTATUS"	VARCHAR(1),
CONSTRAINT "PKTIMEOFOTHERGAME" PRIMARY KEY ("IMATCH_CNT")
);

CREATE GENERATOR "OTHRESULTINFO_GEN";

/* Table: RESULTINFO, Owner: FANNY */

CREATE TABLE "OTHRESULTINFO" 
(
  "RESULT_ID"	INTEGER NOT NULL,
  "MATCH_CNT"	INTEGER,
  "LEAGUE"	CHAR(24),
  "ACT"	CHAR(1),
  "MATCHSTATE"	CHAR(1),
  "RES_FLAG"	CHAR(1),
  "RES_PERIOD"	CHAR(2),
  "RES_TIME"	CHAR(3),
  "H_SCR"	CHAR(2),
  "G_SCR"	CHAR(2),
  "FLAG"	CHAR(1),
  "ALERT"	CHAR(1),
  "PLAYER"	CHAR(20),
  "HOST_PLAYER"	CHAR(15),
  "HOST_PLAYERNO"	CHAR(2),
  "GUEST_PLAYER"	CHAR(15),
  "GUEST_PLAYERNO"	CHAR(2),
  "HOSTPK"	CHAR(30),
  "GUESTPK"	CHAR(30)
);
SET TERM ^ ;


/* Triggers only will work for SQL triggers */

CREATE TRIGGER "AUTOINC_OTHRESULTINFO" FOR "OTHRESULTINFO" 
ACTIVE BEFORE INSERT POSITION 0
as
begin
new.result_id = GEN_ID( OTHRESULTINFO_GEN, 1);
end
 ^

COMMIT WORK ^
SET TERM ;^


INSERT INTO "MSGGP_MAP" ("IMSG_GP", "IMSG_ID", "LASTUPDATE") VALUES (3, 42, current_timestamp);
INSERT INTO "MSGGP_MAP" ("IMSG_GP", "IMSG_ID", "LASTUPDATE") VALUES (902, 42, current_timestamp);

INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('35', 5);
INSERT INTO "MSGROUTE" ("CMSG_TYPE", "IPATH_ID") VALUES ('35', 10);

INSERT INTO "REGISTERED_MSG" ("IMSG_ID", "IREG_ID", "IHOST_ID", "WPARAM", "LPARAM", "TIMESTAMP_FORMAT") VALUES (42, 1, 3, 999999, 99, 'HHmmssfff');