DROP TABLE "FTP_CHECK_MENU";
COMMIT;

CREATE TABLE "FTP_CHECK_MENU" 
(
  "ILINK_NO"	INTEGER NOT NULL,
  "CLINK_NAME"	VARCHAR(20) NOT NULL,
  "CLINK_TYPE"	VARCHAR(3),
  "CLINK_ENABLE"	VARCHAR(1),
 PRIMARY KEY ("ILINK_NO", "CLINK_NAME")
);
COMMIT;

INSERT INTO "FTP_CHECK_MENU" ("ILINK_NO", "CLINK_NAME", "CLINK_TYPE", "CLINK_ENABLE") VALUES (1, '足球賽程', 'FTP', '1');
INSERT INTO "FTP_CHECK_MENU" ("ILINK_NO", "CLINK_NAME", "CLINK_TYPE", "CLINK_ENABLE") VALUES (2, '足球1賽事', 'FTP', '1');
INSERT INTO "FTP_CHECK_MENU" ("ILINK_NO", "CLINK_NAME", "CLINK_TYPE", "CLINK_ENABLE") VALUES (3, '足球2賽事', 'FTP', '1');
COMMIT;