
/* Table: NEWS_CFG, Owner: SYSDBA */

CREATE TABLE "WEB_NEWS_CFG" 
(
  "ISEQNO"	INTEGER NOT NULL,
  "CAPPTYPE"	VARCHAR(20),
  "CINFOTYPE"	VARCHAR(10),
  "CTONE"	VARCHAR(1),
  "ICOLUMN"		INTEGER,
  "IDISPLAY_NUM"	INTEGER default 0,
 PRIMARY KEY ("ISEQNO")
);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (22, '足球資訊1[1]', '吳群立推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (36, '足球資訊1[1]', '丘建威推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (20, '足球資訊1[5]', '分析賽程', 'A', 5, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (21, '足球資訊1[2]', '分析新聞', 'A', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (2, '足球資訊1[10]', '直播', 'A', 10, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (15, '籃球[5]', '分析', 'C', 5, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (16, '籃球[5]', '新聞', 'C', 5, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (17, '籃球[5]', '直播', 'C', 5, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (18, '籃球[5]', '賽程', 'C', 5, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (29, '足球資訊1[1]', '張志德推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (30, '足球資訊1[1]', '歐偉倫推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (31, '足球資訊1[1]', '黃興桂推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (32, '足球資訊1[1]', '彭偉國推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (33, '足球資訊1[1]', '山度士推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (34, '足球資訊1[1]', '蔣世豪推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (35, '足球資訊1[1]', '陳炳安推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (38, '足球資訊1[1]', '丁偉傑推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (39, '足球資訊1[2]', '足彩', 'A', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (101, '馬會資訊1[1]', '吳群立推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (102, '馬會資訊1[1]', '丘建威推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (103, '馬會資訊1[1]', '張志德推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (104, '馬會資訊1[1]', '歐偉倫推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (105, '馬會資訊1[1]', '黃興桂推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (106, '馬會資訊1[1]', '彭偉國推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (107, '馬會資訊1[1]', '山度士推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (108, '馬會資訊1[1]', '蔣世豪推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (109, '馬會資訊1[1]', '陳炳安推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (110, '馬會資訊1[1]', '丁偉傑推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (40, '高爾夫球[1]', '高球賽程', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (41, '高爾夫球[1]', '高球比數', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (42, '高爾夫球[1]', '高球賽果', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (43, '高爾夫球[1]', '高球分析', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (44, '高爾夫球[1]', '高球排名', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (45, '高爾夫球[1]', '高球新聞', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (46, '高爾夫球[1]', '高球直播', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (47, '高爾夫球[1]', '高球賽事', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (48, '網球[1]', '網球賽程', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (49, '網球[1]', '網球比數', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (50, '網球[1]', '網球賽果', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (51, '網球[1]', '網球分析', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (52, '網球[1]', '網球排名', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (53, '網球[1]', '網球新聞', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (54, '網球[1]', '網球直播', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (55, '網球[1]', '網球賽事', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (111, '馬會資訊1[5]', '分析賽程', 'A', 5, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (5, '其他運動[2]', '棒球新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (6, '其他運動[2]', '體操新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (7, '其他運動[2]', '桌球新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (8, '其他運動[2]', '田徑新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (9, '其他運動[2]', '游泳新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (10, '其他運動[2]', '排球新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (11, '其他運動[2]', '乒乓新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (12, '其他運動[2]', '羽球新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (60, '其他運動[2]', '風帆新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (61, '其他運動[2]', '跳水新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (13, '其他運動[2]', '單車新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "IHDRIDSTART", "IHDRIDEND", "CTONE", "CCAPCODE", "ICOLUMN", "IDISPLAY_NUM") VALUES (14, '其他運動[2]', '賽車新聞', 'C', 2, 1);


/* Local DataBase  */
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (22, '足球資訊1[1]', '吳群立推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (36, '足球資訊1[1]', '丘建威推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (20, '足球資訊1[5]', '分析賽程', 'A', 5, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (21, '足球資訊1[2]', '分析新聞', 'A', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (2, '足球資訊1[10]', '直播', 'A', 10, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (15, '籃球[5]', '分析', 'C', 5, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (16, '籃球[5]', '新聞', 'C', 5, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (17, '籃球[5]', '直播', 'C', 5, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (18, '籃球[5]', '賽程', 'C', 5, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (29, '足球資訊1[1]', '張志德推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (30, '足球資訊1[1]', '歐偉倫推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (31, '足球資訊1[1]', '黃興桂推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (32, '足球資訊1[1]', '彭偉國推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (33, '足球資訊1[1]', '山度士推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (34, '足球資訊1[1]', '蔣世豪推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (35, '足球資訊1[1]', '陳炳安推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (38, '足球資訊1[1]', '丁偉傑推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (39, '足球資訊1[2]', '足彩', 'A', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (101, '馬會資訊1[1]', '吳群立推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (102, '馬會資訊1[1]', '丘建威推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (103, '馬會資訊1[1]', '張志德推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (104, '馬會資訊1[1]', '歐偉倫推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (105, '馬會資訊1[1]', '黃興桂推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (106, '馬會資訊1[1]', '彭偉國推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (107, '馬會資訊1[1]', '山度士推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (108, '馬會資訊1[1]', '蔣世豪推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (109, '馬會資訊1[1]', '陳炳安推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (110, '馬會資訊1[1]', '丁偉傑推介', 'A', 1, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (40, '高爾夫球[1]', '高球賽程', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (41, '高爾夫球[1]', '高球比數', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (42, '高爾夫球[1]', '高球賽果', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (43, '高爾夫球[1]', '高球分析', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (44, '高爾夫球[1]', '高球排名', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (45, '高爾夫球[1]', '高球新聞', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (46, '高爾夫球[1]', '高球直播', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (47, '高爾夫球[1]', '高球賽事', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (48, '網球[1]', '網球賽程', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (49, '網球[1]', '網球比數', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (50, '網球[1]', '網球賽果', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (51, '網球[1]', '網球分析', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (52, '網球[1]', '網球排名', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (53, '網球[1]', '網球新聞', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (54, '網球[1]', '網球直播', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (55, '網球[1]', '網球賽事', 'A', 1, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (111, '馬會資訊1[5]', '分析賽程', 'A', 5, 0);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (5, '其他運動[2]', '棒球新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (6, '其他運動[2]', '體操新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (7, '其他運動[2]', '桌球新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (8, '其他運動[2]', '田徑新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (9, '其他運動[2]', '游泳新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (10, '其他運動[2]', '排球新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (11, '其他運動[2]', '乒乓新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (12, '其他運動[2]', '羽球新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (60, '其他運動[2]', '風帆新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (61, '其他運動[2]', '跳水新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (13, '其他運動[2]', '單車新聞', 'C', 2, 1);
INSERT INTO "WEB_NEWS_CFG" ("ISEQNO", "CAPPTYPE", "CINFOTYPE", "CTONE", "ICOLUMN", "IDISPLAY_NUM") VALUES (14, '其他運動[2]', '賽車新聞', 'C', 2, 1);