ALTER TABLE LIVEODDS_INFO
    ALTER COLUMN CHANDICAP1 TYPE varchar(4),
    ALTER COLUMN CHANDICAP2 TYPE varchar(4),
    ALTER COLUMN CTOTALSCORE TYPE varchar(7); 
COMMIT;

ALTER TABLE LOG_LIVEODDS
    ALTER COLUMN TOTALSCORE TYPE varchar(7);
COMMIT;
