CREATE GENERATOR IPMUX_ID_GEN;
SET GENERATOR IPMUX_ID_GEN TO 0;
COMMIT;

CREATE TABLE IPMUX_MACHINE_CFG 
(
  IMACHINE_ID	INTEGER NOT NULL,
  CMACHINE_IP	VARCHAR(15),
  IMACHINE_PORT	INTEGER,
  CCHANNEL	VARCHAR(15),
  CREMARK	VARCHAR(30),
CONSTRAINT PKIPMUXCFG PRIMARY KEY (IMACHINE_ID)
);
grant all on IPMUX_MACHINE_CFG to public;
commit;

CREATE INDEX IPMUXCFGX1 ON IPMUX_MACHINE_CFG(CREMARK);

SET TERM !! ;
create trigger AUTO_IPMUX_ID for IPMUX_MACHINE_CFG
before insert as
begin
new.IMACHINE_ID = GEN_ID(IPMUX_ID_GEN, 1);
end!!
SET TERM ;!!
commit;

Remark: Local Test
insert into IPMUX_MACHINE_CFG (CMACHINE_IP, IMACHINE_PORT, CCHANNEL, CREMARK) values ('127.0.0.1', 14141, '279.6625', 'Live Place M/S Queue Control');

Remark: Dev Test
insert into IPMUX_MACHINE_CFG (CMACHINE_IP, IMACHINE_PORT, CCHANNEL, CREMARK) values ('127.0.0.1', 14141, '279.6625', 'Live Place M/S Queue Control');

Remark: Production
insert into IPMUX_MACHINE_CFG (CMACHINE_IP, IMACHINE_PORT, CCHANNEL, CREMARK) values ('127.0.0.1', 14141, '279.6625', 'Live Place M/S Queue Control');