create table MSGREG_LVPL_CFG
(
  CPAGER VARCHAR(10) NOT NULL,
  IMSG_ID	INTEGER NOT NULL,
  IDB_ID INTEGER NOT NULL,
  IQUEUE_ID INTEGER NOT NULL,
  IENABLED INTEGER default 0,
  PRIMARY KEY (CPAGER, IMSG_ID, IDB_ID, IQUEUE_ID)
);
grant all on MSGREG_LVPL_CFG to public;
commit;

INSERT INTO MSGREG_LVPL_CFG VALUES ('GOGO1', 1, 1, 1, 1);
INSERT INTO MSGREG_LVPL_CFG VALUES ('GOGO1', 1, 1, 2, 1);
INSERT INTO MSGREG_LVPL_CFG VALUES ('GOGO1', 1, 1, 3, 1);
INSERT INTO MSGREG_LVPL_CFG VALUES ('GOGO1', 1, 1, 4, 1);
INSERT INTO MSGREG_LVPL_CFG VALUES ('GOGO1', 2, 1, 1, 0);
INSERT INTO MSGREG_LVPL_CFG VALUES ('GOGO1', 2, 1, 2, 0);
INSERT INTO MSGREG_LVPL_CFG VALUES ('GOGO1', 2, 1, 3, 0);
INSERT INTO MSGREG_LVPL_CFG VALUES ('GOGO1', 2, 1, 4, 0);
INSERT INTO MSGREG_LVPL_CFG VALUES ('HKJC', 1, 2, 1, 0);
INSERT INTO MSGREG_LVPL_CFG VALUES ('HORSE', 1, 1, 1, 0);
INSERT INTO MSGREG_LVPL_CFG VALUES ('HORSE', 2, 1, 1, 0);
commit;