create table QUEUE_SQLCFG
(
  IQUEUE_ID INTEGER NOT NULL,
  CCHANNEL VARCHAR(20),
  CSQL	VARCHAR(200),
  PRIMARY KEY (IQUEUE_ID)
);
grant all on QUEUE_SQLCFG to public;
commit;

INSERT INTO QUEUE_SQLCFG (IQUEUE_ID, CCHANNEL, CSQL) VALUES (1, 'HK_QUEUE', 'INSERT INTO HK_QUEUE (IPRIORITY, CHDRID, CQUERY, CCAPCODE, BINQUERY) VALUES (?, ?, ?, ?, ?)');
INSERT INTO QUEUE_SQLCFG (IQUEUE_ID, CCHANNEL, CSQL) VALUES (2, 'CHK_QUEUE', 'INSERT INTO CHK_QUEUE (IPRIORITY, CHDRID, CQUERY, CCAPCODE, BINQUERY) VALUES (?, ?, ?, ?, ?)');
INSERT INTO QUEUE_SQLCFG (IQUEUE_ID, CCHANNEL, CSQL) VALUES (3, 'ST_QUEUE', 'INSERT INTO ST_QUEUE (IPRIORITY, CHDRID, CQUERY, CCAPCODE, BINQUERY) VALUES (?, ?, ?, ?, ?)');
INSERT INTO QUEUE_SQLCFG (IQUEUE_ID, CCHANNEL, CSQL) VALUES (4, 'MAC_QUEUE', 'INSERT INTO MAC_QUEUE (IPRIORITY, CHDRID, CQUERY, CCAPCODE, BINQUERY) VALUES (?, ?, ?, ?, ?)');
INSERT INTO QUEUE_SQLCFG (IQUEUE_ID, CCHANNEL, CSQL) VALUES (5, 'CHK2G_QUEUE', 'INSERT INTO CHK2G_QUEUE (IPRIORITY, CHDRID, CQUERY, CCAPCODE, BINQUERY) VALUES (?, ?, ?, ?, ?)');
commit;